import type { LangKey } from '../../types/language';

const INITIAL_KEYS: LangKey[] = [
  'WrongNumber',
  'SentAppCode',
  'LoginJustSentSms',
  'LoginHeaderPassword',
  'LoginEnterPasswordDescription',
  'StartText',
  'LoginPhonePlaceholder',
  'LoginNext',
  'LoginQRLogin',
  'LoginQRTitle',
  'LoginQRHelp1',
  'LoginQRHelp2',
  'LoginQRHelp2',
  'LoginQRHelp3',
  'LoginQRCancel',
  'LoginPasskey',
  'YourName',
  'LoginRegisterDesc',
  'LoginRegisterFirstNamePlaceholder',
  'LoginRegisterLastNamePlaceholder',
  'LoginSelectCountryTitle',
  'CountryNone',
  'PleaseEnterPassword',
  'ErrorPhoneNumberInvalid',
  'ErrorCodeInvalid',
  'ErrorIncorrectPassword',
  'ErrorPasswordFlood',
  'ErrorPhoneBanned',
  'ErrorFloodTime',
  'ErrorUnexpected',
  'ErrorUnexpectedMessage',
];

export default INITIAL_KEYS;
