// This file is generated by dev/generateLangTypes.ts. Do not edit it manually.

export interface LangPair {
  'Month1': undefined;
  'Month2': undefined;
  'Month3': undefined;
  'Month4': undefined;
  'Month5': undefined;
  'Month6': undefined;
  'Month7': undefined;
  'Month8': undefined;
  'Month9': undefined;
  'Month10': undefined;
  'Month11': undefined;
  'Month12': undefined;
  'GroupLeaveGroup': undefined;
  'DeleteChatUser': undefined;
  'AccDescrGroup': undefined;
  'AccDescrChannel': undefined;
  'Nothing': undefined;
  'SendActionRecordVideo': undefined;
  'SendActionUploadVideo': undefined;
  'SendActionRecordAudio': undefined;
  'SendActionUploadAudio': undefined;
  'SendActionUploadPhoto': undefined;
  'SendActionUploadFile': undefined;
  'PlayingGame': undefined;
  'SendActionRecordRound': undefined;
  'SendActionUploadRound': undefined;
  'SendActionChooseSticker': undefined;
  'SetUrlInUse': undefined;
  'UsernameInUse': undefined;
  'CreateGroupError': undefined;
  'PasscodeControllerErrorCurrent': undefined;
  'LimitReachedPublicLinksLocked': undefined;
  'LimitReachedPublicLinksPremium': undefined;
  'PremiumPreviewLimits': undefined;
  'PremiumPreviewReactions': undefined;
  'PremiumPreviewStickers': undefined;
  'PremiumPreviewNoAds': undefined;
  'PremiumPreviewVoiceToText': undefined;
  'PremiumPreviewProfileBadge': undefined;
  'PremiumPreviewDownloadSpeed': undefined;
  'PremiumPreviewUploads': undefined;
  'PremiumPreviewAdvancedChatManagement': undefined;
  'PremiumPreviewAnimatedProfiles': undefined;
  'PremiumPreviewReactionsDescription': undefined;
  'PremiumPreviewStickersDescription': undefined;
  'PremiumPreviewNoAdsDescription': undefined;
  'PremiumPreviewVoiceToTextDescription': undefined;
  'PremiumPreviewProfileBadgeDescription': undefined;
  'PremiumPreviewDownloadSpeedDescription': undefined;
  'PremiumPreviewUploadsDescription': undefined;
  'PremiumPreviewAdvancedChatManagementDescription': undefined;
  'PremiumPreviewAnimatedProfilesDescription': undefined;
  'SendMessage': undefined;
  'ConversationDefaultRestrictedMedia': undefined;
  'AccDescrVoiceMessage': undefined;
  'BotSettings': undefined;
  'Privacy': undefined;
  'BotHelp': undefined;
  'ContextCopyImage': undefined;
  'ContextCopyMessageLink': undefined;
  'ProfileCopyPhone': undefined;
  'ContextCopySelected': undefined;
  'ContextCopyText': undefined;
  'CallMessageVideoIncomingDeclined': undefined;
  'CallMessageVideoOutgoingMissed': undefined;
  'CallMessageVideoIncomingMissed': undefined;
  'CallMessageVideoOutgoing': undefined;
  'CallMessageVideoIncoming': undefined;
  'CallMessageIncomingDeclined': undefined;
  'CallMessageOutgoingMissed': undefined;
  'CallMessageIncomingMissed': undefined;
  'CallMessageOutgoing': undefined;
  'CallMessageIncoming': undefined;
  'FinalResults': undefined;
  'QuizPoll': undefined;
  'AnonymousQuizPoll': undefined;
  'PublicPoll': undefined;
  'AnonymousPoll': undefined;
  'AccDescrReactionMentionDown': undefined;
  'AccDescrMentionDown': undefined;
  'AccDescrPageDown': undefined;
  'ChannelPrivate': undefined;
  'ChannelPrivateInfo': undefined;
  'ChannelPublic': undefined;
  'ChannelPublicInfo': undefined;
  'MegaPrivate': undefined;
  'MegaPrivateInfo': undefined;
  'MegaPublic': undefined;
  'MegaPublicInfo': undefined;
  'ChannelType': undefined;
  'GroupType': undefined;
  'ChannelPrivateLinkHelp': undefined;
  'MegaPrivateLinkHelp': undefined;
  'ChannelUsernameCreatePublicLinkHelp': undefined;
  'GroupUsernameCreatePublicLinkHelp': undefined;
  'UserRestrictionsNoSend': undefined;
  'UserRestrictionsNoSendMedia': undefined;
  'UserRestrictionsNoSendStickers': undefined;
  'UserRestrictionsNoEmbedLinks': undefined;
  'UserRestrictionsNoSendPolls': undefined;
  'UserRestrictionsNoChangeInfo': undefined;
  'UserRestrictionsInviteUsers': undefined;
  'UserRestrictionsPinMessages': undefined;
  'StatsMessageInteractionsTitle': undefined;
  'StatsGroupGrowthTitle': undefined;
  'StatsGroupMembersTitle': undefined;
  'StatsGroupLanguagesTitle': undefined;
  'StatsGroupMessagesTitle': undefined;
  'StatsGroupActionsTitle': undefined;
  'StatsGroupTopHoursTitle': undefined;
  'ChannelStatsGraphGrowth': undefined;
  'ChannelStatsGraphFollowers': undefined;
  'ChannelStatsGraphNotifications': undefined;
  'ChannelStatsGraphViewsByHours': undefined;
  'ChannelStatsGraphViewsBySource': undefined;
  'ChannelStatsGraphNewFollowersBySource': undefined;
  'ChannelStatsGraphLanguage': undefined;
  'ChannelStatsGraphInteractions': undefined;
  'StatsMessageViews': undefined;
  'StatsMessagePrivateShares': undefined;
  'StatsMessagePublicShares': undefined;
  'StatsGroupMembers': undefined;
  'StatsGroupMessages': undefined;
  'StatsGroupViewers': undefined;
  'StatsGroupPosters': undefined;
  'ChannelStatsOverviewFollowers': undefined;
  'ChannelStatsOverviewEnabledNotifications': undefined;
  'ChannelStatsOverviewViewsPerPost': undefined;
  'ChannelStatsOverviewSharesPerPost': undefined;
  'WrongNumber': undefined;
  'SentAppCode': undefined;
  'LoginJustSentSms': undefined;
  'Code': undefined;
  'LoginHeaderPassword': undefined;
  'LoginEnterPasswordDescription': undefined;
  'StartText': undefined;
  'LoginPhonePlaceholder': undefined;
  'LoginNext': undefined;
  'LoginQRLogin': undefined;
  'LoginQRTitle': undefined;
  'LoginQRHelp1': undefined;
  'LoginQRHelp2': undefined;
  'LoginQRHelp3': undefined;
  'LoginQRCancel': undefined;
  'YourName': undefined;
  'LoginRegisterDesc': undefined;
  'LoginRegisterFirstNamePlaceholder': undefined;
  'LoginRegisterLastNamePlaceholder': undefined;
  'Next': undefined;
  'LoginSelectCountryTitle': undefined;
  'CountryNone': undefined;
  'VoipGroupVoiceChat': undefined;
  'AccDescrMoreOptions': undefined;
  'AccExitFullscreen': undefined;
  'AccSwitchToFullscreen': undefined;
  'VoipChatStopScreenCapture': undefined;
  'VoipChatStartScreenCapture': undefined;
  'VoipGroupLeaveAlertEndChat': undefined;
  'VoipSpeaker': undefined;
  'VoipCamera': undefined;
  'VoipGroupLeave': undefined;
  'VoipGroupEndAlertTitle': undefined;
  'VoipGroupLeaveAlertTitle': undefined;
  'VoipGroupEndAlertText': undefined;
  'VoipGroupLeaveAlertText': undefined;
  'VoipGroupEndChat': undefined;
  'VoipGroupEnd': undefined;
  'Cancel': undefined;
  'ThisIsYou': undefined;
  'VoipGroupMutedForMe': undefined;
  'WantsToSpeak': undefined;
  'Speaking': undefined;
  'Listening': undefined;
  'VoipGroupInviteMember': undefined;
  'VoipGroupCancelRaiseHand': undefined;
  'VoipGroupOpenProfile': undefined;
  'VoipGroupAllowToSpeak': undefined;
  'VoipMute': undefined;
  'VoipGroupUnmuteForMe': undefined;
  'VoipGroupMuteForMe': undefined;
  'VoipGroupUserRemove': undefined;
  'Back': undefined;
  'VoipChatJoin': undefined;
  'CallStatusHanging': undefined;
  'CallStatusRequesting': undefined;
  'CallStatusRinging': undefined;
  'CallStatusIncoming': undefined;
  'CallStatusWaiting': undefined;
  'CallStatusExchanging': undefined;
  'CallMuteAudio': undefined;
  'CallUnmuteAudio': undefined;
  'CallStopVideo': undefined;
  'CallStartVideo': undefined;
  'VoipFlip': undefined;
  'CallScreencast': undefined;
  'CallAccept': undefined;
  'CallDecline': undefined;
  'CallEndCall': undefined;
  'CallRateLabel': undefined;
  'CallRateComment': undefined;
  'Send': undefined;
  'SponsoredMessageInfo': undefined;
  'SponsoredMessageInfoDescription1': undefined;
  'SponsoredMessageInfoDescription2': undefined;
  'SponsoredMessageInfoDescription3': undefined;
  'SponsoredMessageAlertLearnMoreUrl': undefined;
  'SponsoredMessageInfoDescription4': undefined;
  'Close': undefined;
  'Phone': undefined;
  'Username': undefined;
  'UserBio': undefined;
  'Info': undefined;
  'SetUrlPlaceholder': undefined;
  'Notifications': undefined;
  'SavedMessagesInfo': undefined;
  'BlockedListNotFound': undefined;
  'TextCopied': undefined;
  'WalletAddressCopied': undefined;
  'Copy': undefined;
  'DeleteAndStop': undefined;
  'DeleteForAll': undefined;
  'DeleteSingleMessagesTitle': undefined;
  'AreYouSureDeleteSingleMessage': undefined;
  'ConversationDeleteMessagesForEveryone': undefined;
  'ChatListDeleteForCurrentUser': undefined;
  'Delete': undefined;
  'FakeMessage': undefined;
  'ScamMessage': undefined;
  'SendWithoutSound': undefined;
  'SetReminder': undefined;
  'ScheduleMessage': undefined;
  'Updating': undefined;
  'SelectChat': undefined;
  'PinMessageAlertChannel': undefined;
  'PinMessageAlert': undefined;
  'PinMessageAlertChat': undefined;
  'PinMessageAlertTitle': undefined;
  'DialogPin': undefined;
  'ConversationPinMessageAlertPinAndNotifyMembers': undefined;
  'SavedMessages': undefined;
  'AccDescrPrevious': undefined;
  'ReportReasonSpam': undefined;
  'ReportReasonViolence': undefined;
  'ReportReasonPornography': undefined;
  'ReportReasonChildAbuse': undefined;
  'ReportPeerReasonCopyright': undefined;
  'ReportReasonOther': undefined;
  'ReportMessageTitle': undefined;
  'ReportPeerReport': undefined;
  'ReportReasonDescription': undefined;
  'ReportButton': undefined;
  'StickersRemoveFromFavorites': undefined;
  'StickersAddToFavorites': undefined;
  'ViewPackPreview': undefined;
  'DeleteFromRecent': undefined;
  'AccDescrStickerSet': undefined;
  'ChatPanelUnpinAllMessages': undefined;
  'DialogUnpin': undefined;
  'ArchivedChats': undefined;
  'FilterAddTo': undefined;
  'Draft': undefined;
  'FilterAllChatsShort': undefined;
  'FilterAllChats': undefined;
  'CreateNewContact': undefined;
  'FilterNoChatsToDisplay': undefined;
  'ChatListEmptyChatListFilterText': undefined;
  'ChatEmptyChat': undefined;
  'ChatListEmptyChatListEditFilter': undefined;
  'UpdateTelegram': undefined;
  'AccDescrOpenMenu2': undefined;
  'SettingsTipsUsername': undefined;
  'SearchFriends': undefined;
  'Search': undefined;
  'Contacts': undefined;
  'Settings': undefined;
  'MenuNightMode': undefined;
  'SettingsDisableNightTheme': undefined;
  'SettingsEnableNightTheme': undefined;
  'TelegramPremium': undefined;
  'New': undefined;
  'TelegramFeatures': undefined;
  'ShortcutsControllerOthersLockByPasscode': undefined;
  'GroupAddMembers': undefined;
  'SendMessageTo': undefined;
  'NewChannel': undefined;
  'NewGroup': undefined;
  'AddPhoto': undefined;
  'EnterChannelName': undefined;
  'GroupName': undefined;
  'DescriptionOptionalPlaceholder': undefined;
  'DescriptionInfo': undefined;
  'ChannelIntroCreateChannel': undefined;
  'NewMessageTitle': undefined;
  'ChatListSearchNoResults': undefined;
  'ChatListSearchNoResultsDescription': undefined;
  'ChatListSearchShowLess': undefined;
  'ChatListSearchShowMore': undefined;
  'DialogListSearchSectionDialogs': undefined;
  'DialogListSearchSectionGlobal': undefined;
  'SearchMessages': undefined;
  'Recent': undefined;
  'BlockedUsersBlockUser': undefined;
  'FilterChatTypes': undefined;
  'FilterChats': undefined;
  'FilterIncludeInfo': undefined;
  'FilterNameHint': undefined;
  'FilterInclude': undefined;
  'FilterAddChats': undefined;
  'FilterExclude': undefined;
  'CreateNewFilterInfo': undefined;
  'CreateNewFilter': undefined;
  'Filters': undefined;
  'FilterRecommended': undefined;
  'Add': undefined;
  'EnterNewPasscode': undefined;
  'Continue': undefined;
  'ReEnterYourPasscode': undefined;
  'PasscodeControllerCurrentPlaceholder': undefined;
  'PleaseEnterNewFirstPassword': undefined;
  'PasscodeControllerReEnterPasscodePlaceholder': undefined;
  'PasscodeChange': undefined;
  'PasscodeTurnOff': undefined;
  'EnablePasscode': undefined;
  'SessionPreviewTitle': undefined;
  'SessionPreviewTerminateSession': undefined;
  'PrivacySettingsLastSeen': undefined;
  'SessionPreviewApp': undefined;
  'SessionPreviewIp': undefined;
  'SessionPreviewLocation': undefined;
  'SessionPreviewIpDesc': undefined;
  'AuthSessionsViewAcceptTitle': undefined;
  'SessionPreviewAcceptSecret': undefined;
  'SessionPreviewAcceptCalls': undefined;
  'AuthSessionsCurrentSession': undefined;
  'TerminateAllSessions': undefined;
  'OtherSessions': undefined;
  'TerminateOldSessionHeader': undefined;
  'IfInactiveFor': undefined;
  'AreYouSureSessions': undefined;
  'WebSessionsTitle': undefined;
  'AuthSessionsLogOut': undefined;
  'AuthSessionsViewBrowser': undefined;
  'AuthSessionsViewLocationInfo': undefined;
  'AuthSessionsLogOutApplications': undefined;
  'AuthKeepSignedIn': undefined;
  'AuthTitle': undefined;
  'ClearOtherWebSessionsHelp': undefined;
  'AreYouSureWebSessions': undefined;
  'AutoDownloadMaxFileSize': undefined;
  'AutoDownloadSettingsContacts': undefined;
  'AutoDownloadSettingsPrivateChats': undefined;
  'AutoDownloadSettingsGroupChats': undefined;
  'AutoDownloadSettingsChannels': undefined;
  'AutoDownloadPhotosTitle': undefined;
  'AutoDownloadVideosTitle': undefined;
  'AutoDownloadFilesTitle': undefined;
  'AutoplayMedia': undefined;
  'GifsTab2': undefined;
  'DataAndStorageAutoplayVideos': undefined;
  'FirstName': undefined;
  'LastName': undefined;
  'SettingsAboutBio': undefined;
  'UsernameHelp': undefined;
  'UsernameLink': undefined;
  'SettingsExperimentalAbout': undefined;
  'EmptyChatAppearanceLight': undefined;
  'EmptyChatAppearanceDark': undefined;
  'EmptyChatAppearanceSystem': undefined;
  'SettingsSendEnter': undefined;
  'SettingsSendCmdenter': undefined;
  'SettingsSendCtrlenter': undefined;
  'SettingsSendEnterDescription': undefined;
  'SettingsSendPlusEnterDescription': undefined;
  'SettingsTimeFormat': undefined;
  'SettingsTimeFormat12': undefined;
  'SettingsTimeFormat24': undefined;
  'SettingsKeyboard': undefined;
  'SettingsTray': undefined;
  'SettingsOfflineNotificationUnsupported': undefined;
  'TextSize': undefined;
  'ChatBackground': undefined;
  'Theme': undefined;
  'AccDescrStickers': undefined;
  'DoubleTapSetting': undefined;
  'SuggestStickers': undefined;
  'LoopAnimatedStickers': undefined;
  'UploadImage': undefined;
  'SetColor': undefined;
  'ThemeResetToDefaults': undefined;
  'BackgroundBlurred': undefined;
  'SettingsInformation': undefined;
  'General': undefined;
  'DataSettings': undefined;
  'PrivacySettings': undefined;
  'Language': undefined;
  'SettingsExperimental': undefined;
  'PrivacyPhone': undefined;
  'PrivacyLastSeen': undefined;
  'PrivacyProfilePhoto': undefined;
  'PrivacyForwards': undefined;
  'AutodownloadGroupChats': undefined;
  'AlwaysShareWith': undefined;
  'NeverShareWith': undefined;
  'SessionsTitle': undefined;
  'OtherWebSessions': undefined;
  'BlockedUsers': undefined;
  'TwoStepVerification': undefined;
  'PleaseEnterCurrentPassword': undefined;
  'PleaseReEnterPassword': undefined;
  'PasswordHint': undefined;
  'RecoveryEmailTitle': undefined;
  'TwoStepVerificationPasswordSet': undefined;
  'Passcode': undefined;
  'PasscodeControllerDisableTitle': undefined;
  'PasscodeControllerChangeTitle': undefined;
  'FilterNew': undefined;
  'FilterEdit': undefined;
  'FilterDelete': undefined;
  'FilterShare': undefined;
  'AutoDeleteConfirm': undefined;
  'LogOutTitle': undefined;
  'AccDescrGoBack': undefined;
  'SureLogout': undefined;
  'AccountSettingsLogout': undefined;
  'TelegramGeneralSettingsViewController': undefined;
  'UserInfoNotificationsEnabled': undefined;
  'UserInfoNotificationsDisabled': undefined;
  'AutodownloadPrivateChats': undefined;
  'NotificationsForPrivateChats': undefined;
  'MessagePreview': undefined;
  'FilterGroups': undefined;
  'NotificationsForGroups': undefined;
  'FilterChannels': undefined;
  'NotificationsForChannels': undefined;
  'PhoneOther': undefined;
  'ContactJoined': undefined;
  'P2PEverybody': undefined;
  'P2PContacts': undefined;
  'P2PNobody': undefined;
  'PrivacySettingsWebSessions': undefined;
  'PasswordOn': undefined;
  'PasswordOff': undefined;
  'PrivacyTitle': undefined;
  'PrivacyPhoneTitle': undefined;
  'LastSeenTitle': undefined;
  'PrivacyProfilePhotoTitle': undefined;
  'WhoCanCallMe': undefined;
  'PrivacyP2P': undefined;
  'PrivacyForwardsTitle': undefined;
  'WhoCanAddMe': undefined;
  'NewChatsFromNonContacts': undefined;
  'ArchiveAndMute': undefined;
  'ArchiveAndMuteInfo': undefined;
  'SettingsSensitiveTitle': undefined;
  'SettingsSensitiveDisableFiltering': undefined;
  'SettingsSensitiveAbout': undefined;
  'BlockedUsersInfo': undefined;
  'NoBlocked': undefined;
  'BlockContact': undefined;
  'CustomHelp': undefined;
  'PrivacyExceptions': undefined;
  'AlwaysAllow': undefined;
  'EditAdminAddUsers': undefined;
  'NeverAllow': undefined;
  'AlwaysAllowPlaceholder': undefined;
  'NeverAllowPlaceholder': undefined;
  'PleaseEnterPassword': undefined;
  'PasswordHintPlaceholder': undefined;
  'TwoStepVerificationPasswordSetInfo': undefined;
  'TwoStepVerificationPasswordReturnSettings': undefined;
  'YourEmailCode': undefined;
  'EnabledPasswordText': undefined;
  'ChangePassword': undefined;
  'TurnPasswordOff': undefined;
  'SetRecoveryEmail': undefined;
  'YourEmailSkip': undefined;
  'YourEmailSkipWarning': undefined;
  'YourEmailSkipWarningText': undefined;
  'SetAdditionalPasswordInfo': undefined;
  'EditAdminTransferSetPassword': undefined;
  'BotOpenPageTitle': undefined;
  'FilterDeleteAlert': undefined;
  'RequestToJoinChannelSentDescription': undefined;
  'RequestToJoinGroupSentDescription': undefined;
  'ChannelJoin': undefined;
  'JoinGroup': undefined;
  'MemberRequestsRequestToJoinChannel': undefined;
  'MemberRequestsRequestToJoinGroup': undefined;
  'MemberRequestsRequestToJoinDescriptionChannel': undefined;
  'MemberRequestsRequestToJoinDescriptionGroup': undefined;
  'ShareYouPhoneNumberTitle': undefined;
  'AreYouSureShareMyContactInfoBot': undefined;
  'OK': undefined;
  'ForwardTo': undefined;
  'AttachGame': undefined;
  'JumpToDate': undefined;
  'FloodWait': undefined;
  'PasscodeWrong': undefined;
  'PasscodeEnterPasscodePlaceholder': undefined;
  'MobileHidden': undefined;
  'NewContactShare': undefined;
  'ContactPhone': undefined;
  'NewContact': undefined;
  'Done': undefined;
  'LimitReached': undefined;
  'IncreaseLimit': undefined;
  'LimitFree': undefined;
  'LimitPremium': undefined;
  'TelegramPremiumSubscribedTitle': undefined;
  'AboutPremiumDescription': undefined;
  'AboutPremiumDescription2': undefined;
  'OpenUrlTitle': undefined;
  'BotWebViewOpenBot': undefined;
  'WebAppReloadPage': undefined;
  'WebAppRemoveBot': undefined;
  'WebAppAddToAttachmentAdd': undefined;
  'AccActionDownload': undefined;
  'Forward': undefined;
  'MediaZoomOut': undefined;
  'MediaZoomIn': undefined;
  'PeerInfoReportProfileVideo': undefined;
  'PeerInfoReportProfilePhoto': undefined;
  'MediaviewProfilePhoto': undefined;
  'AccActionPlay': undefined;
  'AttachAudio': undefined;
  'NewContactAdd': undefined;
  'NewContactBlock': undefined;
  'ReportSpamAndLeave': undefined;
  'ChatConfirmReportSpamChannel': undefined;
  'Block': undefined;
  'DeleteThisChat': undefined;
  'Caption': undefined;
  'AttachmentMenuPhotoOrVideo': undefined;
  'AttachDocument': undefined;
  'Poll': undefined;
  'SendMessageAsTitle': undefined;
  'Message': undefined;
  'RecentStickers': undefined;
  'PollsChooseQuestion': undefined;
  'PollsChooseAnswers': undefined;
  'NewPoll': undefined;
  'Create': undefined;
  'OptionHint': undefined;
  'CreatePollAddOption': undefined;
  'PollsChooseCorrect': undefined;
  'AskAQuestion': undefined;
  'PollOptions': undefined;
  'PollAnonymous': undefined;
  'PollMultiple': undefined;
  'PollQuiz': undefined;
  'PollsSolutionTitle': undefined;
  'CreatePollExplanationInfo': undefined;
  'VoipGroupPersonalAccount': undefined;
  'MenuStickers': undefined;
  'MenuAnimations': undefined;
  'MenuStars': undefined;
  'MenuSendGift': undefined;
  'MenuTelegramFaq': undefined;
  'MenuPrivacyPolicy': undefined;
  'MenuAskText': undefined;
  'SettingsPerformanceSliderTitle': undefined;
  'SettingsPerformanceSliderSubtitle': undefined;
  'SettingsPerformanceSliderLow': undefined;
  'SettingsPerformanceSliderMedium': undefined;
  'SettingsPerformanceSliderCustom': undefined;
  'SettingsPerformanceSliderHigh': undefined;
  'SettingsPerformanceInterfaceAnimations': undefined;
  'SettingsPerformanceStickers': undefined;
  'SettingsPerformanceMediaAutoplay': undefined;
  'SettingsPerformancePageTransitions': undefined;
  'SettingsPerformanceSending': undefined;
  'SettingsPerformanceMediaViewer': undefined;
  'SettingsPerformanceComposer': undefined;
  'SettingsPerformanceContextAnimation': undefined;
  'SettingsPerformanceContextBlur': undefined;
  'SettingsPerformanceRightColumn': undefined;
  'SettingsPerformanceThanos': undefined;
  'SettingsPerformanceAnimatedEmoji': undefined;
  'SettingsPerformanceLoopStickers': undefined;
  'SettingsPerformanceReactionEffects': undefined;
  'SettingsPerformanceStickerEffects': undefined;
  'SettingsPerformanceAutoplayGif': undefined;
  'SettingsPerformanceAutoplayVideo': undefined;
  'FavoriteStickers': undefined;
  'PremiumStickers': undefined;
  'GroupStickers': undefined;
  'ErrorSendRestrictedStickersAll': undefined;
  'ErrorPhoneNumberInvalid': undefined;
  'ErrorCodeInvalid': undefined;
  'ErrorEmailCodeInvalid': undefined;
  'ErrorIncorrectPassword': undefined;
  'ErrorPasswordFlood': undefined;
  'ErrorPhoneBanned': undefined;
  'ErrorUnexpected': undefined;
  'ErrorEmailUnconfirmed': undefined;
  'ErrorEmailHashExpired': undefined;
  'ErrorNewSaltInvalid': undefined;
  'ErrorPasswordChanged': undefined;
  'ErrorPasswordMissing': undefined;
  'ErrorUnspecified': undefined;
  'NoStickers': undefined;
  'ClearRecentEmoji': undefined;
  'TextFormatAddLinkTitle': undefined;
  'Save': undefined;
  'ConversationEmptyPlaceholder': undefined;
  'ConversationGreetingText': undefined;
  'ConversationDeleteManyMessages': undefined;
  'AreYouSureDeleteFewMessages': undefined;
  'ProfileJoinChannel': undefined;
  'ProfileJoinGroup': undefined;
  'ChannelJoinRequest': undefined;
  'BotStart': undefined;
  'BotRestart': undefined;
  'SubscribeRequests': undefined;
  'MemberRequests': undefined;
  'AddContact': undefined;
  'Call': undefined;
  'VideoCall': undefined;
  'ChatsUnmute': undefined;
  'ChatsMute': undefined;
  'StartVoipChat': undefined;
  'VoipGroupJoinCall': undefined;
  'ViewDiscussion': undefined;
  'ProfileViewChannel': undefined;
  'ReportSelectMessages': undefined;
  'Statistics': undefined;
  'EventLogFilterPinnedMessages': undefined;
  'UnpinMessageAlertTitle': undefined;
  'PinnedMessageTitleSingle': undefined;
  'AccPinnedMessages': undefined;
  'AccUnpinMessage': undefined;
  'LeaveAComment': undefined;
  'PollsStopWarning': undefined;
  'PollsStopSure': undefined;
  'PaymentTestInvoice': undefined;
  'AttachLiveLocation': undefined;
  'NoWordsRecognized': undefined;
  'ViaBot': undefined;
  'DiscussChannel': undefined;
  'ForwardedMessage': undefined;
  'ContextForwardMsg': undefined;
  'MessageScheduleSend': undefined;
  'MessageScheduleEditTime': undefined;
  'Reply': undefined;
  'Edit': undefined;
  'AddToFavorites': undefined;
  'ContextSaveGif': undefined;
  'PollsRetract': undefined;
  'PollsStop': undefined;
  'ContextCancelDownload': undefined;
  'MediaDownload': undefined;
  'CommonSelect': undefined;
  'ContextReportMsg': undefined;
  'ConversationContextMenuNoViews': undefined;
  'HideAd': undefined;
  'EditedMessage': undefined;
  'CallAgain': undefined;
  'CallBack': undefined;
  'PollSubmitVotes': undefined;
  'PollViewResults': undefined;
  'ChatQuizTotalVotesEmpty': undefined;
  'ChatPollTotalVotesResultEmpty': undefined;
  'Vote': undefined;
  'MessageRecommendedLabel': undefined;
  'SponsoredMessageAd': undefined;
  'SponsoredMessageAdWhatIsThis': undefined;
  'PremiumStickerTooltip': undefined;
  'ViewAction': undefined;
  'Loading': undefined;
  'NoMessages': undefined;
  'BotInfoTitle': undefined;
  'UnreadMessages': undefined;
  'DiscussionStarted': undefined;
  'MessageScheduledUntilOnline': undefined;
  'ChatForwardActionHeader': undefined;
  'ConversationReportMessages': undefined;
  'ContextCopySelectedItems': undefined;
  'EditAdminGroupDeleteMessages': undefined;
  'Reminders': undefined;
  'MessageMetaEdited': undefined;
  'MessageMetaApproximate': undefined;
  'MessageMetaImported': undefined;
  'ImportedInfo': undefined;
  'ScheduledMessagesEmptyPlaceholder': undefined;
  'ConversationCloudStorageInfoTitle': undefined;
  'ConversationClousStorageInfoDescription1': undefined;
  'ConversationClousStorageInfoDescription2': undefined;
  'ConversationClousStorageInfoDescription3': undefined;
  'ConversationClousStorageInfoDescription4': undefined;
  'EmptyGroupInfoTitle': undefined;
  'EmptyGroupInfoSubtitle': undefined;
  'EmptyGroupInfoLine2': undefined;
  'EmptyGroupInfoLine3': undefined;
  'EmptyGroupInfoLine4': undefined;
  'Reactions': undefined;
  'MarkAllAsRead': undefined;
  'PaymentCardNumber': undefined;
  'CheckoutTotalAmount': undefined;
  'PaymentCheckoutMethod': undefined;
  'PaymentCheckoutProvider': undefined;
  'PaymentShippingAddress': undefined;
  'PaymentCheckoutName': undefined;
  'PaymentCheckoutPhoneNumber': undefined;
  'PaymentCheckoutShippingMethod': undefined;
  'CheckoutWebConfirmationTitle': undefined;
  'PaymentCardExpireDate': undefined;
  'PaymentCardTitle': undefined;
  'CheckoutNewCardCardholderNamePlaceholder': undefined;
  'PaymentsCardCvc': undefined;
  'PaymentBillingAddress': undefined;
  'PaymentShippingCountry': undefined;
  'PaymentShippingZipPlaceholder': undefined;
  'PaymentCardSavePaymentInformation': undefined;
  'PaymentShippingInfo': undefined;
  'PaymentShippingMethod': undefined;
  'PaymentCardInfo': undefined;
  'PaymentCheckout': undefined;
  'PaymentReceipt': undefined;
  'PaymentShippingAddress1Placeholder': undefined;
  'PaymentShippingAddress2Placeholder': undefined;
  'PaymentShippingCityPlaceholder': undefined;
  'PaymentShippingStatePlaceholder': undefined;
  'PaymentShippingReceiver': undefined;
  'PaymentShippingName': undefined;
  'PaymentShippingEmailPlaceholder': undefined;
  'PaymentShippingPhoneNumber': undefined;
  'PaymentShippingSave': undefined;
  'PaymentShippingSaveInfo': undefined;
  'ChannelAddUsers': undefined;
  'GroupRemovedRemove': undefined;
  'BoxRemove': undefined;
  'NoGIFsFound': undefined;
  'ChannelAddToChannel': undefined;
  'ChannelAddToGroup': undefined;
  'DismissRequest': undefined;
  'DescriptionPlaceholder': undefined;
  'TypePublic': undefined;
  'TypePrivate': undefined;
  'Discussion': undefined;
  'DiscussionUnlink': undefined;
  'GroupInfoInviteLinks': undefined;
  'ChannelSignMessages': undefined;
  'ChannelAdministrators': undefined;
  'ChannelSubscribers': undefined;
  'ChannelBlockedUsers': undefined;
  'ChannelDelete': undefined;
  'LeaveChannel': undefined;
  'ChannelDeleteAlert': undefined;
  'ChannelLeaveAlert': undefined;
  'ChannelCreator': undefined;
  'ChannelAdmin': undefined;
  'EventLog': undefined;
  'EventLogInfoDetailChannel': undefined;
  'EventLogInfoDetail': undefined;
  'ChannelManagementAddModerator': undefined;
  'ChannelVisibilityForwardingEnabled': undefined;
  'ChannelVisibilityForwardingDisabled': undefined;
  'RevokeLink': undefined;
  'RevokeAlert': undefined;
  'RevokeButton': undefined;
  'ChannelVisibilityForwardingChannelTitle': undefined;
  'ChannelVisibilityForwardingGroupTitle': undefined;
  'ChannelVisibilityForwardingChannelInfo': undefined;
  'ChannelVisibilityForwardingGroupInfo': undefined;
  'Unblock': undefined;
  'NoBlockedChannel2': undefined;
  'NoBlockedGroup2': undefined;
  'ChannelEditAdminPermissionBanUsers': undefined;
  'DiscussionUnlinkGroup': undefined;
  'DiscussionUnlinkChannel': undefined;
  'ChannelDiscussionGroupLinkGroup': undefined;
  'DiscussionChannelHelp': undefined;
  'DiscussionCreateGroup': undefined;
  'DiscussionChannelHelp2': undefined;
  'DiscussionLinkGroup': undefined;
  'ChannelSettingsJoinTitle': undefined;
  'ChannelSettingsJoinToSend': undefined;
  'ChannelSettingsJoinRequest': undefined;
  'ChannelSettingsJoinRequestInfo': undefined;
  'ChannelSettingsJoinToSendInfo': undefined;
  'LinkedChannel': undefined;
  'ChannelPermissions': undefined;
  'GroupMembers': undefined;
  'ChatHistory': undefined;
  'DeleteMega': undefined;
  'AreYouSureDeleteAndExit': undefined;
  'DeleteGroupForAll': undefined;
  'EditAdminWhatCanDo': undefined;
  'EditAdminChangeChannelInfo': undefined;
  'EditAdminChangeGroupInfo': undefined;
  'EditAdminPostMessages': undefined;
  'EditAdminEditMessages': undefined;
  'EditAdminDeleteMessages': undefined;
  'EditAdminBanUsers': undefined;
  'EditAdminPinMessages': undefined;
  'EditAdminAddAdmins': undefined;
  'StartVoipChatPermission': undefined;
  'EditAdminSendAnonymously': undefined;
  'ChannelEditAdminCannotEdit': undefined;
  'EditAdminRank': undefined;
  'EditAdminRemoveAdmin': undefined;
  'ChannelAdminDismiss': undefined;
  'ChannelPermissionsHeader': undefined;
  'UserRestrictionsSend': undefined;
  'UserRestrictionsSendMedia': undefined;
  'UserRestrictionsSendStickers': undefined;
  'UserRestrictionsSendPolls': undefined;
  'UserRestrictionsEmbedLinks': undefined;
  'UserRestrictionsChangeInfo': undefined;
  'ChannelAddException': undefined;
  'EventLogAllEvents': undefined;
  'EventLogFilterNewAdmins': undefined;
  'EventLogFilterNewMembers': undefined;
  'EventLogFilterChannelInfo': undefined;
  'EventLogFilterDeletedMessages': undefined;
  'EventLogFilterEditedMessages': undefined;
  'EventLogFilterLeavingMembers': undefined;
  'ChannelManagementTitle': undefined;
  'EventLogAllAdmins': undefined;
  'UserRestrictionsCanDo': undefined;
  'UserRestrictionsBlock': undefined;
  'ApproveNewMembers': undefined;
  'ApproveNewMembersDescription': undefined;
  'LinkNameHint': undefined;
  'LinkNameHelp': undefined;
  'LimitByPeriod': undefined;
  'NoLimit': undefined;
  'GroupInviteExpireCustom': undefined;
  'TimeLimitHelp': undefined;
  'LimitNumberOfUses': undefined;
  'GroupInviteUsageCustom': undefined;
  'UsesLimitHelp': undefined;
  'SaveLink': undefined;
  'CreateLink': undefined;
  'LinkCopied': undefined;
  'NoOneJoined': undefined;
  'NoOneJoinedYet': undefined;
  'CopyLink': undefined;
  'ExpiredLink': undefined;
  'LinkCreatedeBy': undefined;
  'Revoked': undefined;
  'LinkLimitReached': undefined;
  'InviteLinkExpired': undefined;
  'Permanent': undefined;
  'DeleteLink': undefined;
  'PrimaryLinkHelpChannel': undefined;
  'PrimaryLinkHelp': undefined;
  'PublicLink': undefined;
  'CreatePermanentLinkTitle': undefined;
  'CreateNewLink': undefined;
  'ManageLinksInfoHelp': undefined;
  'RevokedLinks': undefined;
  'DeleteAllRevokedLinks': undefined;
  'DeleteAllRevokedLinkHelp': undefined;
  'DeleteAll': undefined;
  'DeleteLinkHelp': undefined;
  'NoMemberRequests': undefined;
  'NoSubscribeRequestsDescription': undefined;
  'NoMemberRequestsDescription': undefined;
  'EnableReactions': undefined;
  'UserInfoFirstNamePlaceholder': undefined;
  'UserInfoLastNamePlaceholder': undefined;
  'DeleteContact': undefined;
  'AreYouSureDeleteContact': undefined;
  'ChannelBlockUser': undefined;
  'ContextRemoveFromGroup': undefined;
  'NoGroupsInCommon': undefined;
  'MediaFileEmpty': undefined;
  'MediaLinkEmpty': undefined;
  'MediaSongEmpty': undefined;
  'MediaAudioEmpty': undefined;
  'SharedMediaEmptyTitle': undefined;
  'PollResults': undefined;
  'ChannelAddSubscribers': undefined;
  'ChannelTypeHeader': undefined;
  'GroupTypeHeader': undefined;
  'GroupInfoAdminLog': undefined;
  'EditAdminRights': undefined;
  'SetAsAdmin': undefined;
  'UserRestrictions': undefined;
  'GroupInviteTitle': undefined;
  'EditLink': undefined;
  'NewLink': undefined;
  'InviteLink': undefined;
  'SearchStickersHint': undefined;
  'SearchGifsTitle': undefined;
  'ChannelStatsTitle': undefined;
  'GroupStatsTitle': undefined;
  'StatsMessageTitle': undefined;
  'SharedMedia': undefined;
  'CommonBack': undefined;
  'CommonClose': undefined;
  'DlgSearchForMessages': undefined;
  'SearchNoResults': undefined;
  'GraphZoomOut': undefined;
  'ChannelStatsRecentHeader': undefined;
  'StatisticOverview': undefined;
  'Stickers': undefined;
  'StickersInstalled': undefined;
  'StickersInstall': undefined;
  'CropImage': undefined;
  'ReportPeerAlertSuccess': undefined;
  'WebAppAddToAttachmentUnavailableError': undefined;
  'LimitReachedFavoriteGifsSubtitlePremium': undefined;
  'LimitReachedFavoriteStickersSubtitlePremium': undefined;
  'StickerPackErrorNotFound': undefined;
  'ContactsPhoneNumberNotRegistred': undefined;
  'NoUsernameFound': undefined;
  'PrivateChannelInaccessible': undefined;
  'HiddenName': undefined;
  'ChannelPersmissionDeniedSendMessagesForever': undefined;
  'ChannelPersmissionDeniedSendMessagesDefaultRestrictedText': undefined;
  'Chats': undefined;
  'FilterBots': undefined;
  'FilterContacts': undefined;
  'FilterNonContacts': undefined;
  'FromYou': undefined;
  'InDlgAlbum': undefined;
  'AttachPhoto': undefined;
  'AttachGif': undefined;
  'AttachVideo': undefined;
  'AttachSticker': undefined;
  'AttachMusic': undefined;
  'AttachContact': undefined;
  'MessageLocation': undefined;
  'MessageLiveLocation': undefined;
  'ServiceNotifications': undefined;
  'Bot': undefined;
  'ALongTimeAgo': undefined;
  'WithinAMonth': undefined;
  'WithinAWeek': undefined;
  'LastSeenOffline': undefined;
  'LastSeenJustNow': undefined;
  'Online': undefined;
  'Lately': undefined;
  'VoipMutedTapedForSpeak': undefined;
  'VoipMutedByAdmin': undefined;
  'VoipUnmute': undefined;
  'VoipTapToMute': undefined;
  'Weekday1': undefined;
  'Weekday2': undefined;
  'Weekday3': undefined;
  'Weekday4': undefined;
  'Weekday5': undefined;
  'Weekday6': undefined;
  'Weekday7': undefined;
  'WeekdayMonday': undefined;
  'WeekdayTuesday': undefined;
  'WeekdayWednesday': undefined;
  'WeekdayThursday': undefined;
  'WeekdayFriday': undefined;
  'WeekdaySaturday': undefined;
  'WeekdaySunday': undefined;
  'WeekdayToday': undefined;
  'WeekdayYesterday': undefined;
  'User': undefined;
  'SecretChat': undefined;
  'ChatListFilterErrorEmpty': undefined;
  'ChatListFilterErrorTitleEmpty': undefined;
  'FilterMuted': undefined;
  'FilterRead': undefined;
  'FilterArchived': undefined;
  'GroupsAndChannelsLimitTitle': undefined;
  'PinChatsLimitTitle': undefined;
  'PublicLinksLimitTitle': undefined;
  'SavedGifsLimitTitle': undefined;
  'FavoriteStickersLimitTitle': undefined;
  'BioLimitTitle': undefined;
  'CaptionsLimitTitle': undefined;
  'FoldersLimitTitle': undefined;
  'ChatPerFolderLimitTitle': undefined;
  'BioLimitSubtitle': undefined;
  'CaptionsLimitSubtitle': undefined;
  'TelegramPremiumUserDialogSubtitle': undefined;
  'TelegramPremiumSubscribedSubtitle': undefined;
  'TelegramPremiumSubtitle': undefined;
  'EditMessageAriaLabel': undefined;
  'Emoji1': undefined;
  'Emoji2': undefined;
  'Emoji3': undefined;
  'Emoji4': undefined;
  'Emoji5': undefined;
  'Emoji6': undefined;
  'Emoji7': undefined;
  'Emoji8': undefined;
  'GroupInfoDeleteAndExit': undefined;
  'HidAccount': undefined;
  'ConversationViewBot': undefined;
  'ConversationViewPost': undefined;
  'ConversationViewChannel': undefined;
  'Telegram': undefined;
  'ChatListFilterAddToFolder': undefined;
  'UnpinFromTop': undefined;
  'PinToTop': undefined;
  'MarkAsRead': undefined;
  'MarkAsUnread': undefined;
  'Unarchive': undefined;
  'Archive': undefined;
  'WaitingForNetwork': undefined;
  'ScheduleSendWhenOnline': undefined;
  'VoipIncoming': undefined;
  'LiveLocationUpdatedJustNow': undefined;
  'RightNow': undefined;
  'AudioPause': undefined;
  'AudioPlay': undefined;
  'ToggleUserNotifications': undefined;
  'ToggleChatNotifications': undefined;
  'ChannelInaccessible': undefined;
  'GroupInaccessible': undefined;
  'AriaPasswordToggle': undefined;
  'NothingFound': undefined;
  'SetUrlShort': undefined;
  'SetUrlLong': undefined;
  'SetUrlInvalid': undefined;
  'UsernameShort': undefined;
  'UsernameLong': undefined;
  'UsernameInvalid': undefined;
  'AriaCodeWordWrap': undefined;
  'AriaBackToChatList': undefined;
  'NoContactsFound': undefined;
  'ContactListEmpty': undefined;
  'AriaNewChannelContinue': undefined;
  'AriaNewGroupContinue': undefined;
  'NewChatTitleEmptyError': undefined;
  'NewChannelTitleEmptyError': undefined;
  'NewChatTooManyUsers': undefined;
  'AriaCreateGroup': undefined;
  'SearchAllMessagesTab': undefined;
  'SearchMediaTab': undefined;
  'SearchLinksTab': undefined;
  'SearchGifsTab': undefined;
  'SearchFilesTab': undefined;
  'SearchMusicTab': undefined;
  'SearchVoiceTab': undefined;
  'SearchGroupsTab': undefined;
  'RecentChatsClear': undefined;
  'EditProfileNoFirstName': undefined;
  'AriaEditProfilePhoto': undefined;
  'LaunchConfetti': undefined;
  'SettingsAnimations': undefined;
  'SettingsAnimationsDescription': undefined;
  'SettingsAnimationsLow': undefined;
  'SettingsAnimationsMedium': undefined;
  'SettingsAnimationsHigh': undefined;
  'Settings12HourFormat': undefined;
  'Settings24HourFormat': undefined;
  'SettingsSendCtrlEnterDescription': undefined;
  'AriaMoreButton': undefined;
  'RecoveryEmailCode': undefined;
  'NotificationsWeb': undefined;
  'NotificationsOffline': undefined;
  'NotificationsSound': undefined;
  'SettingsPasswordEqual': undefined;
  'SettingsSaveChanges': undefined;
  'SettingsFolderCreate': undefined;
  'SettingsFoldersEmpty': undefined;
  'SettingsPasscodeSuccess': undefined;
  'SettingsPasscodeEnabled': undefined;
  'SettingsPasscodeStart1': undefined;
  'SettingsPasscodeStart2': undefined;
  'CurrentPasswordPlaceholder': undefined;
  'TooManyTabsTitle': undefined;
  'TooManyTabsDescription': undefined;
  'TooManyTabsReload': undefined;
  'SlowmodeEnabled': undefined;
  'SomethingWentWrong': undefined;
  'VideoPlayerBuffering': undefined;
  'VideoPlayerFullscreen': undefined;
  'PlayerVolume': undefined;
  'PlayerPlaybackRate': undefined;
  'AudioPlayerPrevious': undefined;
  'AudioPlayerNext': undefined;
  'AudioPlayerClose': undefined;
  'DeleteForMeDescription': undefined;
  'DeleteForEveryoneDescription': undefined;
  'AriaSearchInChat': undefined;
  'PinnedConfirmUnpin': undefined;
  'RestictionReasonPrivateChat': undefined;
  'RestictionReasonPrivateChannel': undefined;
  'BotInfoImageAlt': undefined;
  'AriaExitMessageSelection': undefined;
  'AriaSearchByDate': undefined;
  'AriaCloseAttachmentModal': undefined;
  'AriaAddAttachment': undefined;
  'AttachMenuMediaBlocked': undefined;
  'AriaOpenBotMenu': undefined;
  'AriaOpenSymbolMenu': undefined;
  'AriaComposerOpenScheduled': undefined;
  'AriaComposerCancelVoice': undefined;
  'PreviewEditMessage': undefined;
  'FileDropZoneTitle': undefined;
  'FileDropZoneQuick': undefined;
  'FileDropZoneNoCompression': undefined;
  'GifPickerBlocked': undefined;
  'GifPickerEmpty': undefined;
  'AriaCancelPollCreation': undefined;
  'AriaLabelSearchStickers': undefined;
  'AriaLabelSearchGifs': undefined;
  'FormattingSpoilerAria': undefined;
  'FormattingBoldAria': undefined;
  'FormattingItalicAria': undefined;
  'FormattingMonospaceAria': undefined;
  'FormattingUnderlineAria': undefined;
  'FormattingStrikethroughAria': undefined;
  'FormattingEnterUrl': undefined;
  'PreviewWebPageClose': undefined;
  'MediaLocaltionImageAlt': undefined;
  'MediaPollSolutionAria': undefined;
  'GeneralError': undefined;
  'PaymentsProvidesNotSupported': undefined;
  'ChatMemberListNoAccess': undefined;
  'NoMembersFound': undefined;
  'Profile': undefined;
  'ChannelManagementAddAdminDescription': undefined;
  'GroupManagementAddAdminDescription': undefined;
  'ChannelManagementLinkPrivate': undefined;
  'NoDiscussionsLinked': undefined;
  'ManagementRemoveAdminConfirm': undefined;
  'NoSubscribersFound': undefined;
  'GroupManagementBanUserConfirm': undefined;
  'NoLinksFound': undefined;
  'JoinRequestAcceptAllTitle': undefined;
  'JoinRequestAcceptAllDescription': undefined;
  'JoinRequestRejectAllTitle': undefined;
  'JoinRequestRejectAllDescription': undefined;
  'StatsNoShares': undefined;
  'AvatarChangeTitle': undefined;
  'PleaseWait': undefined;
  'GeneralConfirm': undefined;
  'ImageCropTitle': undefined;
  'NewChatReturnBackAria': undefined;
  'FoldersAllChatsDesc': undefined;
  'RemoveSymbol': undefined;
  'FocusMessage': undefined;
  'HiddenSendersNameDescription': undefined;
  'ShowSenderNames': undefined;
  'ShowSendersName': undefined;
  'HideSenderNames': undefined;
  'HideSendersName': undefined;
  'ConversationForwardOptionsShowCaption': undefined;
  'ShowCaption': undefined;
  'ConversationForwardOptionsHideCaption': undefined;
  'HideCaption': undefined;
  'ChangeRecipient': undefined;
  'DragToSortAria': undefined;
  'MenuReportBug': undefined;
  'MenuBetaChangelog': undefined;
  'MenuSwitchToK': undefined;
  'MenuInstallApp': undefined;
  'RemoveEffect': undefined;
  'ReplyInPrivateMessage': undefined;
  'ProfileOpenAppTerms': undefined;
  'ProfileBotOpenAppInfoLink': undefined;
  'MonetizationInfoTONTitle': undefined;
  'AriaSearchOlderResult': undefined;
  'AriaSearchNewerResult': undefined;
  'StarsTransactionTOSLinkText': undefined;
  'StarsTransactionTOSLink': undefined;
  'GiftPremiumHeader': undefined;
  'GiftPremiumDescriptionLinkCaption': undefined;
  'GiftPremiumDescriptionLink': undefined;
  'StarsGiftHeader': undefined;
  'StarsGiftHeaderSelf': undefined;
  'StarGiftDescriptionSelf': undefined;
  'GiftLimited': undefined;
  'GiftSoldOut': undefined;
  'GiftMessagePlaceholder': undefined;
  'GiftHideMyName': undefined;
  'GiftHideNameDescriptionChannel': undefined;
  'GiftInfoSent': undefined;
  'GiftInfoReceived': undefined;
  'GiftInfoTitle': undefined;
  'GiftInfoDescriptionFreeUpgrade': undefined;
  'GiftInfoDescriptionUpgraded': undefined;
  'GiftInfoFrom': undefined;
  'GiftInfoDate': undefined;
  'GiftInfoValue': undefined;
  'GiftInfoConvertTitle': undefined;
  'GiftInfoConvertDescription2': undefined;
  'GiftInfoSavedHide': undefined;
  'GiftInfoSavedShow': undefined;
  'GiftInfoAvailability': undefined;
  'GiftInfoFirstSale': undefined;
  'GiftInfoLastSale': undefined;
  'GiftInfoSoldOutTitle': undefined;
  'GiftInfoSoldOutDescription': undefined;
  'GiftInfoSenderHidden': undefined;
  'GiftInfoOwner': undefined;
  'GiftAttributeModel': undefined;
  'GiftAttributeBackdrop': undefined;
  'GiftAttributeSymbol': undefined;
  'GiftInfoStatus': undefined;
  'GiftInfoStatusNonUnique': undefined;
  'GiftInfoViewUpgraded': undefined;
  'GiftInfoUpgradeBadge': undefined;
  'GiftInfoUpgradeForFree': undefined;
  'GiftInfoWithdraw': undefined;
  'GiftInfoWear': undefined;
  'GiftInfoTakeOff': undefined;
  'GiftInfoTransfer': undefined;
  'GiftTransferTitle': undefined;
  'GiftTransferTON': undefined;
  'GiftTransferConfirmButtonFree': undefined;
  'GiftUpgradeUniqueTitle': undefined;
  'GiftUpgradeUniqueDescription': undefined;
  'GiftUpgradeTransferableTitle': undefined;
  'GiftUpgradeTransferableDescription': undefined;
  'GiftUpgradeTradeableTitle': undefined;
  'GiftUpgradeTradeableDescription': undefined;
  'GiftUpgradeTitle': undefined;
  'GiftUpgradeTextOwn': undefined;
  'GiftUpgradeKeepDetails': undefined;
  'GiftUpgradedTitle': undefined;
  'GiftUpgradedDescription': undefined;
  'GiftMakeUniqueAcc': undefined;
  'GiftMakeUniqueLink': undefined;
  'GiftWithdrawTitle': undefined;
  'GiftWithdrawSubmit': undefined;
  'AllGiftsCategory': undefined;
  'LimitedGiftsCategory': undefined;
  'StockGiftsCategory': undefined;
  'PremiumGiftDescription': undefined;
  'StarsReactionLinkText': undefined;
  'StarsReactionLink': undefined;
  'ActionStarGiftDisplaying': undefined;
  'ActionStarGiftChannelDisplaying': undefined;
  'ActionStarGiftDescriptionUpgrade': undefined;
  'ActionStarGiftUpgraded': undefined;
  'ActionStarGiftUnpack': undefined;
  'GiftTo': undefined;
  'GiftFrom': undefined;
  'ReceivedGift': undefined;
  'SentGift': undefined;
  'StarsSubscribeInfoLinkText': undefined;
  'StarsSubscribeInfoLink': undefined;
  'StarsBalance': undefined;
  'OpenApp': undefined;
  'PopularApps': undefined;
  'SearchApps': undefined;
  'Apps': undefined;
  'AreYouSureCloseMiniApps': undefined;
  'CloseMiniApps': undefined;
  'DoNotAskAgain': undefined;
  'PaymentInfoDone': undefined;
  'VideoConversionTitle': undefined;
  'VideoConversionText': undefined;
  'VideoConversionDone': undefined;
  'VideoConversionView': undefined;
  'BotSuggestedStatusTitle': undefined;
  'BotSuggestedStatusUpdated': undefined;
  'BotDownloadFileTitle': undefined;
  'BotDownloadFileButton': undefined;
  'PrivacyGifts': undefined;
  'PrivacyGiftsTitle': undefined;
  'PrivacyGiftsInfo': undefined;
  'PrivacyValueBots': undefined;
  'CustomShareGiftsInfo': undefined;
  'AllChatsSearchContext': undefined;
  'PrivateChatsSearchContext': undefined;
  'GroupChatsSearchContext': undefined;
  'ChannelsSearchContext': undefined;
  'FolderLinkSubtitleNew': undefined;
  'FolderLinkSubtitleAlready': undefined;
  'FolderLinkAddFolder': undefined;
  'SearchTabChats': undefined;
  'SearchTabChannels': undefined;
  'SearchTabApps': undefined;
  'SearchTabMedia': undefined;
  'SearchTabLinks': undefined;
  'SearchTabFiles': undefined;
  'SearchTabMusic': undefined;
  'SearchTabVoice': undefined;
  'SearchTabMessages': undefined;
  'StarsTransactionsAll': undefined;
  'StarsTransactionsIncoming': undefined;
  'StarsTransactionsOutgoing': undefined;
  'ProfileTabSavedDialogs': undefined;
  'ProfileTabStories': undefined;
  'ProfileTabStoriesArchive': undefined;
  'ProfileTabGifts': undefined;
  'ProfileTabSubscribers': undefined;
  'ProfileTabMembers': undefined;
  'ProfileTabBotPreview': undefined;
  'ProfileTabMedia': undefined;
  'ProfileTabFiles': undefined;
  'ProfileTabLinks': undefined;
  'ProfileTabMusic': undefined;
  'ProfileTabVoice': undefined;
  'ProfileTabSharedGroups': undefined;
  'ProfileTabSimilarChannels': undefined;
  'ProfileTabSimilarBots': undefined;
  'ActionUnsupportedTitle': undefined;
  'ActionUnsupportedDescription': undefined;
  'UnlockMoreSimilarBots': undefined;
  'GiftWasNotFound': undefined;
  'ViewButtonRequestJoin': undefined;
  'ViewButtonMessage': undefined;
  'ViewButtonBot': undefined;
  'ViewButtonVoiceChat': undefined;
  'ViewButtonVoiceChatChannel': undefined;
  'ViewButtonGroup': undefined;
  'ViewButtonChannel': undefined;
  'ViewButtonUser': undefined;
  'ViewButtonBotApp': undefined;
  'ViewChatList': undefined;
  'ViewButtonStory': undefined;
  'ViewButtonBoost': undefined;
  'ViewButtonStickerset': undefined;
  'ViewButtonGiftUnique': undefined;
  'AuthContinueOnThisLanguage': undefined;
  'Share': undefined;
  'GiftSortByDate': undefined;
  'GiftSortByValue': undefined;
  'GiftFilterUnlimited': undefined;
  'GiftFilterLimited': undefined;
  'GiftFilterUnique': undefined;
  'GiftFilterDisplayed': undefined;
  'GiftFilterHidden': undefined;
  'GiftSearchEmpty': undefined;
  'GiftSearchReset': undefined;
  'CheckPasswordTitle': undefined;
  'CheckPasswordPlaceholder': undefined;
  'CheckPasswordDescription': undefined;
  'UniqueStatusBenefitsDescription': undefined;
  'UniqueStatusBadgeBenefitTitle': undefined;
  'UniqueStatusBadgeDescription': undefined;
  'UniqueStatusProfileDesignBenefitTitle': undefined;
  'UniqueStatusProfileDesignDescription': undefined;
  'UniqueStatusProofOfOwnershipBenefitTitle': undefined;
  'UniqueStatusProofOfOwnershipDescription': undefined;
  'UniqueStatusWearButton': undefined;
  'CollectibleStatusesCategory': undefined;
}

export interface LangPairWithVariables<V extends unknown = LangVariable> {
  'ChatServiceGroupUpdatedPinnedMessage1': {
    'user': V;
    'message': V;
  };
  'MessagePinnedGenericMessage': {
    'user': V;
  };
  'UserTyping': {
    'user': V;
  };
  'UserActionWatchingAnimations': {
    'emoji': V;
  };
  'SetUrlAvailable': {
    'url': V;
  };
  'UsernameAvailable': {
    'username': V;
  };
  'LimitReachedChatInFolders': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedFileSize': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedFolders': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedPinDialogs': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedPublicLinks': {
    'limit2': V;
  };
  'LimitReachedCommunities': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedChatInFoldersLocked': {
    'limit': V;
  };
  'LimitReachedFileSizeLocked': {
    'limit': V;
  };
  'LimitReachedFoldersLocked': {
    'limit': V;
  };
  'LimitReachedPinDialogsLocked': {
    'limit': V;
  };
  'LimitReachedCommunitiesLocked': {
    'limit': V;
  };
  'LimitReachedChatInFoldersPremium': {
    'limit': V;
  };
  'LimitReachedFileSizePremium': {
    'limit': V;
  };
  'LimitReachedFoldersPremium': {
    'limit': V;
  };
  'LimitReachedPinDialogsPremium': {
    'limit': V;
  };
  'LimitReachedCommunitiesPremium': {
    'limit': V;
  };
  'PremiumPreviewLimitsDescription': {
    'limit1': V;
    'limit2': V;
    'limit3': V;
    'limit4': V;
    'limit5': V;
  };
  'SpeakingWithVolume': {
    'volume': V;
  };
  'CallEmojiKeyTooltip': {
    'user': V;
  };
  'ConversationScheduleMessageSendToday': {
    'time': V;
  };
  'ConversationScheduleMessageSendOn': {
    'date': V;
    'time': V;
  };
  'ChatListDeleteAndLeaveGroupConfirmation': {
    'chat': V;
  };
  'ChannelLeaveAlertWithName': {
    'chat': V;
  };
  'ChatListDeleteChatConfirmation': {
    'chat': V;
  };
  'ChatListDeleteForEveryone': {
    'user': V;
  };
  'ConversationDeleteMessagesFor': {
    'user': V;
  };
  'ConversationPinMessagesFor': {
    'user': V;
  };
  'AutodownloadSizeLimitUpTo': {
    'limit': V;
  };
  'FileSizeMB': {
    'count': V;
  };
  'WebAppAddToAttachmentText': {
    'bot': V;
  };
  'BotPermissionGameAlert': {
    'bot': V;
  };
  'BotOpenPageMessage': {
    'bot': V;
  };
  'NewContactPhoneHiddenText': {
    'user': V;
  };
  'AddContactSharedContactExceptionInfo': {
    'user': V;
  };
  'FileSizeGB': {
    'count': V;
  };
  'SubscribeToPremium': {
    'price': V;
  };
  'TelegramPremiumUserDialogTitle': {
    'user': V;
  };
  'OpenUrlAlert2': {
    'url': V;
  };
  'ConversationOpenBotLinkLogin': {
    'url': V;
    'user': V;
  };
  'ConversationOpenBotLinkAllowMessages': {
    'bot': V;
  };
  'BlockUserTitle': {
    'user': V;
  };
  'UserInfoBlockConfirmationTitle': {
    'user': V;
  };
  'ReportChat': {
    'peer': V;
  };
  'SlowModeHint': {
    'time': V;
  };
  'ErrorFloodTime': {
    'time': V;
  };
  'ErrorPasswordFresh': {
    'time': V;
  };
  'ErrorUnexpectedMessage': {
    'error': V;
  };
  'EditedDate': {
    'date': V;
  };
  'ForwardedDate': {
    'date': V;
  };
  'CallMessageWithDuration': {
    'time': V;
    'duration': V;
  };
  'MessageScheduledOn': {
    'date': V;
  };
  'MessageTooltipEditedDate': {
    'date': V;
  };
  'MessageTooltipForwardedDate': {
    'date': V;
  };
  'EmptyGroupInfoLine1': {
    'count': V;
  };
  'PaymentCheckoutAcceptRecurrent': {
    'bot': V;
  };
  'CheckoutPayPrice': {
    'amount': V;
  };
  'PeerInfoConfirmRemovePeer': {
    'user': V;
  };
  'EditAdminPromotedBy': {
    'user': V;
  };
  'UserRemovedBy': {
    'user': V;
  };
  'DiscussionUnlinkChannelAlert': {
    'chat': V;
  };
  'DiscussionUnlinkGroupAlert': {
    'channel': V;
  };
  'AreYouSureDeleteThisChatWithGroup': {
    'chat': V;
  };
  'LinkExpiresIn': {
    'time': V;
  };
  'InviteLinkExpiresIn': {
    'time': V;
  };
  'UsernameByPhoneNotFound': {
    'phone': V;
  };
  'LimitReachedFavoriteGifs': {
    'count': V;
  };
  'LimitReachedFavoriteGifsSubtitle': {
    'count': V;
  };
  'LimitReachedFavoriteStickers': {
    'count': V;
  };
  'LimitReachedFavoriteStickersSubtitle': {
    'count': V;
  };
  'VoipPeerIncompatible': {
    'user': V;
  };
  'LastSeenTodayAt': {
    'time': V;
  };
  'LastSeenYesterdayAt': {
    'time': V;
  };
  'LastSeenAtDate': {
    'date': V;
  };
  'ChannelPermissionDeniedSendMessagesUntil': {
    'date': V;
  };
  'FormatDateAtTime': {
    'date': V;
    'time': V;
  };
  'GroupsAndChannelsLimitSubtitle': {
    'count': V;
  };
  'PinChatsLimitSubtitle': {
    'count': V;
  };
  'PublicLinksLimitSubtitle': {
    'count': V;
  };
  'SavedGifsLimitSubtitle': {
    'count': V;
  };
  'FavoriteStickersLimitSubtitle': {
    'count': V;
  };
  'FoldersLimitSubtitle': {
    'count': V;
  };
  'ChatPerFolderLimitSubtitle': {
    'count': V;
  };
  'ChatOutgoingContextMixedReactionCount': {
    'count': V;
    'total': V;
  };
  'FileSizeB': {
    'count': V;
  };
  'FileSizeKB': {
    'count': V;
  };
  'MessageTimerShortHours': {
    'count': V;
  };
  'MessageTimerShortDays': {
    'count': V;
  };
  'LiveLocationUpdatedTodayAt': {
    'time': V;
  };
  'MediaViewDownloading': {
    'count': V;
  };
  'ChannelManagementLinkDiscussion': {
    'group': V;
    'channel': V;
  };
  'ProfileOpenAppAbout': {
    'terms': V;
  };
  'ChannelEarnLearnCoinAbout': {
    'link': V;
  };
  'MonetizationBalanceZeroInfo': {
    'link': V;
  };
  'ChannelEarnAbout': {
    'link': V;
  };
  'CreditsBoxHistoryEntryGiftOutAbout': {
    'user': V;
    'link': V;
  };
  'StarsTransactionTOS': {
    'link': V;
  };
  'GiftStarsOutgoing': {
    'user': V;
  };
  'GiftPremiumDescription': {
    'user': V;
    'link': V;
  };
  'StarGiftDescription': {
    'user': V;
  };
  'StarGiftDescriptionChannel': {
    'peer': V;
  };
  'GiftDiscount': {
    'percent': V;
  };
  'GiftSoldCount': {
    'count': V;
  };
  'GiftLeftCount': {
    'count': V;
  };
  'GiftHideNameDescription': {
    'receiver': V;
  };
  'GiftSend': {
    'amount': V;
  };
  'GiftUnique': {
    'title': V;
    'number': V;
  };
  'GiftInfoPeerDescriptionFreeUpgradeOut': {
    'peer': V;
  };
  'GiftInfoPeerConvertDescription': {
    'peer': V;
    'amount': V;
  };
  'GiftInfoSaved': {
    'link': V;
  };
  'GiftInfoHidden': {
    'link': V;
  };
  'GiftInfoChannelSaved': {
    'link': V;
  };
  'GiftInfoChannelHidden': {
    'link': V;
  };
  'GiftInfoIssued': {
    'issued': V;
    'total': V;
  };
  'GiftInfoCollectible': {
    'number': V;
  };
  'GiftInfoPeerOriginalInfo': {
    'peer': V;
    'date': V;
  };
  'GiftInfoPeerOriginalInfoSender': {
    'sender': V;
    'peer': V;
    'date': V;
  };
  'GiftInfoPeerOriginalInfoText': {
    'peer': V;
    'date': V;
    'text': V;
  };
  'GiftInfoPeerOriginalInfoTextSender': {
    'sender': V;
    'peer': V;
    'date': V;
    'text': V;
  };
  'GiftTransferTONBlocked': {
    'time': V;
  };
  'GiftTransferConfirmDescription': {
    'gift': V;
    'peer': V;
    'amount': V;
  };
  'GiftTransferConfirmDescriptionFree': {
    'gift': V;
    'peer': V;
  };
  'GiftTransferConfirmButton': {
    'amount': V;
  };
  'GiftTransferSuccessMessage': {
    'gift': V;
    'peer': V;
  };
  'GiftPeerUpgradeText': {
    'peer': V;
  };
  'GiftUpgradeButton': {
    'amount': V;
  };
  'GiftMakeUnique': {
    'stars': V;
  };
  'GiftMakeUniqueDescription': {
    'user': V;
    'link': V;
  };
  'GiftMakeUniqueDescriptionChannel': {
    'peer': V;
    'link': V;
  };
  'GiftWithdrawDescription': {
    'gift': V;
  };
  'StarsAmount': {
    'amount': V;
  };
  'SendPaidReaction': {
    'amount': V;
  };
  'StarsPay': {
    'amount': V;
  };
  'StarsReactionTerms': {
    'link': V;
  };
  'ActionStarGiftPeerTitle': {
    'peer': V;
    'count': V;
  };
  'ActionStarGiftOutTitle': {
    'count': V;
  };
  'ActionStarGiftPeerOutDescriptionUpgrade': {
    'peer': V;
  };
  'StarsSubscribeInfo': {
    'link': V;
  };
  'StarsPerMonth': {
    'amount': V;
  };
  'EmojiStatusAccessText': {
    'name': V;
  };
  'BotSuggestedStatusFor': {
    'bot': V;
    'duration': V;
  };
  'BotSuggestedStatus': {
    'bot': V;
  };
  'BotDownloadFileDescription': {
    'bot': V;
    'filename': V;
  };
  'StarsSubscribeBotButtonMonth': {
    'amount': V;
  };
  'SearchContextCaption': {
    'type': V;
  };
  'FolderLinkTitleDescription': {
    'folder': V;
    'chats': V;
  };
  'FolderLinkSubtitleAdd': {
    'chats': V;
    'title': V;
  };
  'FolderLinkNotificationDeletedTitle': {
    'title': V;
  };
  'FolderLinkNotificationAddedTitle': {
    'title': V;
  };
  'FolderLinkNotificationUpdatedTitle': {
    'title': V;
  };
  'LocationPermissionText': {
    'name': V;
  };
  'MoreSimilarBotsText': {
    'count': V;
  };
  'UniqueStatusWearTitle': {
    'gift': V;
  };
}

export interface LangPairPlural {
  'DeleteForMeChatHint': undefined;
  'DeleteForEveryoneHint': undefined;
  'PreviewDraggingAddItems': undefined;
}

export interface LangPairPluralWithVariables<V extends unknown = LangVariable> {
  'Participants': {
    'count': V;
  };
  'OnlineCount': {
    'count': V;
  };
  'Subscribers': {
    'count': V;
  };
  'NMembers': {
    'count': V;
  };
  'ChatUnpinAllMessagesConfirmation': {
    'count': V;
  };
  'GroupInfoParticipantCount': {
    'count': V;
  };
  'Weeks': {
    'count': V;
  };
  'Months': {
    'count': V;
  };
  'Users': {
    'count': V;
  };
  'StickerPackStickerCount': {
    'count': V;
  };
  'PreviewSenderSendPhoto': {
    'count': V;
  };
  'PreviewSenderSendVideo': {
    'count': V;
  };
  'PreviewSenderSendAudio': {
    'count': V;
  };
  'PreviewSenderSendFile': {
    'count': V;
  };
  'PinnedMessageTitle': {
    'index': V;
  };
  'Comments': {
    'count': V;
  };
  'ChatContextReactionCount': {
    'count': V;
  };
  'ConversationContextMenuSeen': {
    'count': V;
  };
  'Answer': {
    'count': V;
  };
  'VoiceOverChatMessagesSelected': {
    'count': V;
  };
  'ChatPinnedUnpinAll': {
    'count': V;
  };
  'CommentsCount': {
    'count': V;
  };
  'PinnedMessagesCount': {
    'count': V;
  };
  'Messages': {
    'count': V;
  };
  'MessageTooltipForwards': {
    'count': V;
  };
  'MessageTooltipViews': {
    'count': V;
  };
  'MessageTooltipReplies': {
    'count': V;
  };
  'Hours': {
    'count': V;
  };
  'Days': {
    'count': V;
  };
  'PeopleJoined': {
    'count': V;
  };
  'PeopleCanJoinViaLinkCount': {
    'count': V;
  };
  'CanJoin': {
    'count': V;
  };
  'JoinRequests': {
    'count': V;
  };
  'ChannelStatsViewsCount': {
    'count': V;
  };
  'ChannelStatsSharesCount': {
    'count': V;
  };
  'LastSeenMinutesAgo': {
    'count': V;
  };
  'LastSeenHoursAgo': {
    'count': V;
  };
  'StickerPackRemoveStickerCount': {
    'count': V;
  };
  'StickerPackAddStickerCount': {
    'count': V;
  };
  'Years': {
    'count': V;
  };
  'LiveLocationUpdatedMinutesAgo': {
    'count': V;
  };
  'Seconds': {
    'count': V;
  };
  'Minutes': {
    'count': V;
  };
  'PreviewForwardedMessage': {
    'count': V;
  };
  'SearchMessagesFound': {
    'count': V;
  };
  'ShowMoreChats': {
    'count': V;
  };
  'ShowMoreVoters': {
    'count': V;
  };
  'GiftInfoDescription': {
    'amount': V;
  };
  'GiftInfoPeerDescriptionOut': {
    'peer': V;
    'amount': V;
  };
  'GiftInfoDescriptionUpgrade': {
    'amount': V;
  };
  'GiftInfoDescriptionConverted': {
    'amount': V;
  };
  'GiftInfoPeerDescriptionOutConverted': {
    'peer': V;
    'amount': V;
  };
  'GiftInfoConvert': {
    'amount': V;
  };
  'GiftInfoConvertDescriptionPeriod': {
    'count': V;
  };
  'GiftInfoAvailabilityValue': {
    'count': V;
    'total': V;
  };
  'GiftWithdrawWait': {
    'days': V;
  };
  'StarsAmountText': {
    'amount': V;
  };
  'MiniAppsMoreTabs': {
    'botName': V;
    'count': V;
  };
  'PrizeCredits2': {
    'count': V;
  };
  'ActionStarGiftPeerOutDescription': {
    'peer': V;
    'count': V;
  };
  'ActionStarGiftDescription2': {
    'count': V;
  };
  'StarsSubscribeText': {
    'chat': V;
    'amount': V;
  };
  'StarsSubscribeBotText': {
    'name': V;
    'bot': V;
    'amount': V;
  };
  'FolderLinkTitleDescriptionChats': {
    'count': V;
  };
  'FolderLinkSubtitleAddCount': {
    'count': V;
  };
  'FolderLinkNotificationDeletedSubtitle': {
    'count': V;
  };
  'FolderLinkNotificationAddedSubtitle': {
    'count': V;
  };
  'FolderLinkNotificationUpdatedSubtitle': {
    'count': V;
  };
}
export type RegularLangKey = keyof LangPair;
export type RegularLangKeyWithVariables = keyof LangPairWithVariables;
export type PluralLangKey = keyof LangPairPlural;
export type PluralLangKeyWithVariables = keyof LangPairPluralWithVariables;
export type LangKey = RegularLangKey | RegularLangKeyWithVariables | PluralLangKey | PluralLangKeyWithVariables;
type LangVariable = string | number | undefined;
