// This file is generated by dev/generateLangTypes.ts. Do not edit it manually.

export interface LangPair {
  'Month1': undefined;
  'Month2': undefined;
  'Month3': undefined;
  'Month4': undefined;
  'Month5': undefined;
  'Month6': undefined;
  'Month7': undefined;
  'Month8': undefined;
  'Month9': undefined;
  'Month10': undefined;
  'Month11': undefined;
  'Month12': undefined;
  'GroupLeaveGroup': undefined;
  'DeleteChat': undefined;
  'AccDescrGroup': undefined;
  'AccDescrChannel': undefined;
  'Nothing': undefined;
  'SendActionRecordVideo': undefined;
  'SendActionUploadVideo': undefined;
  'SendActionRecordAudio': undefined;
  'SendActionUploadAudio': undefined;
  'SendActionUploadPhoto': undefined;
  'SendActionUploadFile': undefined;
  'PlayingGame': undefined;
  'SendActionRecordRound': undefined;
  'SendActionUploadRound': undefined;
  'SendActionChooseSticker': undefined;
  'SetUrlInUse': undefined;
  'UsernameInUse': undefined;
  'CreateGroupError': undefined;
  'PasscodeControllerErrorCurrent': undefined;
  'LimitReachedPublicLinksLocked': undefined;
  'LimitReachedPublicLinksPremium': undefined;
  'PremiumPreviewLimits': undefined;
  'PremiumPreviewReactions': undefined;
  'PremiumPreviewStickers': undefined;
  'PremiumPreviewNoAds': undefined;
  'PremiumPreviewVoiceToText': undefined;
  'PremiumPreviewProfileBadge': undefined;
  'PremiumPreviewDownloadSpeed': undefined;
  'PremiumPreviewUploads': undefined;
  'PremiumPreviewAdvancedChatManagement': undefined;
  'PremiumPreviewAnimatedProfiles': undefined;
  'PremiumPreviewReactionsDescription': undefined;
  'PremiumPreviewStickersDescription': undefined;
  'PremiumPreviewNoAdsDescription': undefined;
  'PremiumPreviewVoiceToTextDescription': undefined;
  'PremiumPreviewProfileBadgeDescription': undefined;
  'PremiumPreviewDownloadSpeedDescription': undefined;
  'PremiumPreviewTodoDescription': undefined;
  'PremiumPreviewUploadsDescription': undefined;
  'PremiumPreviewAdvancedChatManagementDescription': undefined;
  'PremiumPreviewAnimatedProfilesDescription': undefined;
  'PremiumLimitAccountsTitle': undefined;
  'PremiumLimitAccountsNoPremium': undefined;
  'PremiumLimitAccounts': undefined;
  'SendMessage': undefined;
  'MessageUnsupported': undefined;
  'ConversationDefaultRestrictedMedia': undefined;
  'AccDescrVoiceMessage': undefined;
  'BotSettings': undefined;
  'Privacy': undefined;
  'BotHelp': undefined;
  'ContextCopyImage': undefined;
  'ContextCopyMessageLink': undefined;
  'ProfileCopyPhone': undefined;
  'ContextCopySelected': undefined;
  'ContextCopyText': undefined;
  'ContextArchiveCollapse': undefined;
  'ContextArchiveExpand': undefined;
  'ContextArchiveToMenu': undefined;
  'CallMessageVideoIncomingDeclined': undefined;
  'CallMessageVideoOutgoingMissed': undefined;
  'CallMessageVideoIncomingMissed': undefined;
  'CallMessageVideoOutgoing': undefined;
  'CallMessageVideoIncoming': undefined;
  'CallMessageIncomingDeclined': undefined;
  'CallMessageOutgoingMissed': undefined;
  'CallMessageIncomingMissed': undefined;
  'CallMessageOutgoing': undefined;
  'CallMessageIncoming': undefined;
  'FinalResults': undefined;
  'QuizPoll': undefined;
  'AnonymousQuizPoll': undefined;
  'PublicPoll': undefined;
  'AnonymousPoll': undefined;
  'AccDescrReactionMentionDown': undefined;
  'AccDescrMentionDown': undefined;
  'AccDescrPageDown': undefined;
  'ChannelPrivate': undefined;
  'ChannelPrivateInfo': undefined;
  'ChannelPublic': undefined;
  'ChannelPublicInfo': undefined;
  'MegaPrivate': undefined;
  'MegaPrivateInfo': undefined;
  'MegaPublic': undefined;
  'MegaPublicInfo': undefined;
  'ChannelType': undefined;
  'GroupType': undefined;
  'ChannelPrivateLinkHelp': undefined;
  'MegaPrivateLinkHelp': undefined;
  'ChannelUsernameCreatePublicLinkHelp': undefined;
  'GroupUsernameCreatePublicLinkHelp': undefined;
  'UserRestrictionsNoSend': undefined;
  'UserRestrictionsNoSendMedia': undefined;
  'UserRestrictionsNoSendStickers': undefined;
  'UserRestrictionsNoEmbedLinks': undefined;
  'UserRestrictionsNoSendPolls': undefined;
  'UserRestrictionsNoChangeInfo': undefined;
  'UserRestrictionsInviteUsers': undefined;
  'UserRestrictionsPinMessages': undefined;
  'ChatPermissionNotAvailable': undefined;
  'StatsMessageInteractionsTitle': undefined;
  'StatsGroupGrowthTitle': undefined;
  'StatsGroupMembersTitle': undefined;
  'StatsGroupLanguagesTitle': undefined;
  'StatsGroupMessagesTitle': undefined;
  'StatsGroupActionsTitle': undefined;
  'StatsGroupTopHoursTitle': undefined;
  'ChannelStatsGraphGrowth': undefined;
  'ChannelStatsGraphFollowers': undefined;
  'ChannelStatsGraphNotifications': undefined;
  'ChannelStatsGraphViewsByHours': undefined;
  'ChannelStatsGraphViewsBySource': undefined;
  'ChannelStatsGraphNewFollowersBySource': undefined;
  'ChannelStatsGraphLanguage': undefined;
  'ChannelStatsGraphInteractions': undefined;
  'StatsMessageViews': undefined;
  'StatsMessagePrivateShares': undefined;
  'StatsMessagePublicShares': undefined;
  'StatsGroupMembers': undefined;
  'StatsGroupMessages': undefined;
  'StatsGroupViewers': undefined;
  'StatsGroupPosters': undefined;
  'ChannelStatsOverviewFollowers': undefined;
  'ChannelStatsOverviewEnabledNotifications': undefined;
  'ChannelStatsOverviewViewsPerPost': undefined;
  'ChannelStatsOverviewSharesPerPost': undefined;
  'WrongNumber': undefined;
  'SentAppCode': undefined;
  'LoginJustSentSms': undefined;
  'Code': undefined;
  'Open': undefined;
  'LoginHeaderPassword': undefined;
  'BotShareMessageShare': undefined;
  'BotShareMessage': undefined;
  'LoginEnterPasswordDescription': undefined;
  'StartText': undefined;
  'LoginPhonePlaceholder': undefined;
  'LoginNext': undefined;
  'LoginQRLogin': undefined;
  'LoginQRTitle': undefined;
  'LoginQRHelp1': undefined;
  'LoginQRHelp2': undefined;
  'LoginQRHelp3': undefined;
  'LoginQRCancel': undefined;
  'LoginPasskey': undefined;
  'YourName': undefined;
  'LoginRegisterDesc': undefined;
  'LoginRegisterFirstNamePlaceholder': undefined;
  'LoginRegisterLastNamePlaceholder': undefined;
  'Next': undefined;
  'LoginSelectCountryTitle': undefined;
  'MenuAddAccount': undefined;
  'CountryNone': undefined;
  'VoipGroupVoiceChat': undefined;
  'AccDescrMoreOptions': undefined;
  'AccExitFullscreen': undefined;
  'AccSwitchToFullscreen': undefined;
  'VoipChatStopScreenCapture': undefined;
  'VoipChatStartScreenCapture': undefined;
  'VoipGroupLeaveAlertEndChat': undefined;
  'VoipSpeaker': undefined;
  'VoipCamera': undefined;
  'VoipGroupLeave': undefined;
  'VoipGroupEndAlertTitle': undefined;
  'VoipGroupLeaveAlertTitle': undefined;
  'VoipGroupEndAlertText': undefined;
  'VoipGroupLeaveAlertText': undefined;
  'VoipGroupEndChat': undefined;
  'VoipGroupEnd': undefined;
  'Cancel': undefined;
  'ThisIsYou': undefined;
  'VoipGroupMutedForMe': undefined;
  'WantsToSpeak': undefined;
  'Speaking': undefined;
  'Listening': undefined;
  'VoipGroupInviteMember': undefined;
  'VoipGroupCancelRaiseHand': undefined;
  'VoipGroupOpenProfile': undefined;
  'VoipGroupAllowToSpeak': undefined;
  'VoipMute': undefined;
  'VoipGroupUnmuteForMe': undefined;
  'VoipGroupMuteForMe': undefined;
  'VoipGroupUserRemove': undefined;
  'Back': undefined;
  'VoipChatJoin': undefined;
  'CallStatusHanging': undefined;
  'CallStatusRequesting': undefined;
  'CallStatusRinging': undefined;
  'CallStatusIncoming': undefined;
  'CallStatusWaiting': undefined;
  'CallStatusExchanging': undefined;
  'CallMuteAudio': undefined;
  'CallUnmuteAudio': undefined;
  'CallStopVideo': undefined;
  'CallStartVideo': undefined;
  'VoipFlip': undefined;
  'CallScreencast': undefined;
  'CallAccept': undefined;
  'CallDecline': undefined;
  'CallEndCall': undefined;
  'CallRateLabel': undefined;
  'CallRateComment': undefined;
  'Send': undefined;
  'SponsoredMessageInfo': undefined;
  'SponsoredMessageInfoDescription1': undefined;
  'SponsoredMessageInfoDescription2': undefined;
  'SponsoredMessageInfoDescription3': undefined;
  'SponsoredMessageAlertLearnMoreUrl': undefined;
  'SponsoredMessageInfoDescription4': undefined;
  'Close': undefined;
  'Phone': undefined;
  'Username': undefined;
  'UserBio': undefined;
  'Info': undefined;
  'SetUrlPlaceholder': undefined;
  'Notifications': undefined;
  'SavedMessagesInfo': undefined;
  'BlockedListNotFound': undefined;
  'TextCopied': undefined;
  'WalletAddressCopied': undefined;
  'Copy': undefined;
  'DeleteAndStop': undefined;
  'ChatNonContactUserSubtitle': undefined;
  'ChatNonContactUserGroups': undefined;
  'ContactInfoRegistration': undefined;
  'ContactInfoNotVerified': undefined;
  'DeleteForAll': undefined;
  'DeleteSingleMessagesTitle': undefined;
  'AreYouSureDeleteSingleMessage': undefined;
  'ConversationDeleteMessagesForEveryone': undefined;
  'ChatListDeleteForCurrentUser': undefined;
  'Delete': undefined;
  'FakeMessage': undefined;
  'ScamMessage': undefined;
  'SendWithoutSound': undefined;
  'SetReminder': undefined;
  'ScheduleMessage': undefined;
  'Updating': undefined;
  'SelectChat': undefined;
  'PinMessageAlertChannel': undefined;
  'PinMessageAlert': undefined;
  'PinMessageAlertChat': undefined;
  'PinMessageAlertTitle': undefined;
  'DialogPin': undefined;
  'ConversationPinMessageAlertPinAndNotifyMembers': undefined;
  'SavedMessages': undefined;
  'AccDescrPrevious': undefined;
  'ReportReasonSpam': undefined;
  'ReportReasonViolence': undefined;
  'ReportReasonPornography': undefined;
  'ReportReasonChildAbuse': undefined;
  'ReportPeerReasonCopyright': undefined;
  'ReportReasonOther': undefined;
  'ReportMessageTitle': undefined;
  'ReportPeerReport': undefined;
  'ReportReasonDescription': undefined;
  'ReportButton': undefined;
  'StickersRemoveFromFavorites': undefined;
  'StickersAddToFavorites': undefined;
  'ViewPackPreview': undefined;
  'DeleteFromRecent': undefined;
  'AccDescrStickerSet': undefined;
  'ChatPanelUnpinAllMessages': undefined;
  'DialogUnpin': undefined;
  'ArchivedChats': undefined;
  'FilterAddTo': undefined;
  'Draft': undefined;
  'ChatDraftPrefix': undefined;
  'FilterAllChatsShort': undefined;
  'FilterAllChats': undefined;
  'CreateNewContact': undefined;
  'FilterNoChatsToDisplay': undefined;
  'ChatListEmptyChatListFilterText': undefined;
  'ChatEmptyChat': undefined;
  'ChatListEmptyChatListEditFilter': undefined;
  'UpdateTelegram': undefined;
  'AriaLabelOpenMenu': undefined;
  'AriaLabelBackChatList': undefined;
  'SettingsTipsUsername': undefined;
  'SearchFriends': undefined;
  'Search': undefined;
  'Contacts': undefined;
  'Settings': undefined;
  'SettingsDisableNightTheme': undefined;
  'SettingsEnableNightTheme': undefined;
  'TelegramPremium': undefined;
  'New': undefined;
  'TelegramFeatures': undefined;
  'ShortcutsControllerOthersLockByPasscode': undefined;
  'GroupAddMembers': undefined;
  'SendMessageTo': undefined;
  'NewChannel': undefined;
  'NewGroup': undefined;
  'AddPhoto': undefined;
  'EnterChannelName': undefined;
  'GroupName': undefined;
  'DescriptionOptionalPlaceholder': undefined;
  'DescriptionInfo': undefined;
  'ChannelIntroCreateChannel': undefined;
  'NewMessageTitle': undefined;
  'ChatListSearchNoResults': undefined;
  'ChatListSearchNoResultsDescription': undefined;
  'ChatListSearchShowLess': undefined;
  'ChatListSearchShowMore': undefined;
  'DialogListSearchSectionDialogs': undefined;
  'DialogListSearchSectionGlobal': undefined;
  'SearchMessages': undefined;
  'Recent': undefined;
  'BlockedUsersBlockUser': undefined;
  'FilterChatTypes': undefined;
  'FilterChats': undefined;
  'FilterColorTitle': undefined;
  'FilterColorHint': undefined;
  'ShowFolderTags': undefined;
  'ShowFolderTagsHint': undefined;
  'TabsPosition': undefined;
  'TabsPositionLeft': undefined;
  'TabsPositionTop': undefined;
  'FilterIncludeInfo': undefined;
  'FilterNameHint': undefined;
  'FilterInclude': undefined;
  'FilterAddChats': undefined;
  'FilterExclude': undefined;
  'CreateNewFilterInfo': undefined;
  'CreateNewFilter': undefined;
  'Filters': undefined;
  'FilterRecommended': undefined;
  'Add': undefined;
  'EnterNewPasscode': undefined;
  'Continue': undefined;
  'ReEnterYourPasscode': undefined;
  'PasscodeControllerCurrentPlaceholder': undefined;
  'PleaseEnterNewFirstPassword': undefined;
  'PasscodeControllerReEnterPasscodePlaceholder': undefined;
  'PasscodeChange': undefined;
  'PasscodeTurnOff': undefined;
  'EnablePasscode': undefined;
  'SessionPreviewTitle': undefined;
  'SessionPreviewTerminateSession': undefined;
  'PrivacySettingsLastSeen': undefined;
  'SessionPreviewApp': undefined;
  'SessionPreviewIp': undefined;
  'SessionPreviewLocation': undefined;
  'SessionPreviewIpDesc': undefined;
  'AuthSessionsViewAcceptTitle': undefined;
  'SessionPreviewAcceptSecret': undefined;
  'SessionPreviewAcceptCalls': undefined;
  'AuthSessionsCurrentSession': undefined;
  'TerminateAllSessions': undefined;
  'OtherSessions': undefined;
  'TerminateOldSessionHeader': undefined;
  'IfInactiveFor': undefined;
  'AreYouSureSessions': undefined;
  'WebSessionsTitle': undefined;
  'AuthSessionsLogOut': undefined;
  'AuthSessionsViewBrowser': undefined;
  'AuthSessionsViewLocationInfo': undefined;
  'AuthSessionsLogOutApplications': undefined;
  'AuthKeepSignedIn': undefined;
  'AuthTitle': undefined;
  'ClearOtherWebSessionsHelp': undefined;
  'AreYouSureWebSessions': undefined;
  'AutoDownloadMaxFileSize': undefined;
  'AutoDownloadSettingsContacts': undefined;
  'AutoDownloadSettingsPrivateChats': undefined;
  'AutoDownloadSettingsGroupChats': undefined;
  'AutoDownloadSettingsChannels': undefined;
  'AutoDownloadPhotosTitle': undefined;
  'AutoDownloadVideosTitle': undefined;
  'AutoDownloadFilesTitle': undefined;
  'AutoplayMedia': undefined;
  'GifsTab2': undefined;
  'DataAndStorageAutoplayVideos': undefined;
  'FirstName': undefined;
  'LastName': undefined;
  'SettingsAboutBio': undefined;
  'UsernameHelp': undefined;
  'UsernameLink': undefined;
  'SettingsExperimentalAbout': undefined;
  'EmptyChatAppearanceLight': undefined;
  'EmptyChatAppearanceDark': undefined;
  'EmptyChatAppearanceSystem': undefined;
  'SettingsSendEnter': undefined;
  'SettingsSendCmdenter': undefined;
  'SettingsSendCtrlenter': undefined;
  'SettingsSendEnterDescription': undefined;
  'SettingsSendPlusEnterDescription': undefined;
  'SettingsTimeFormat': undefined;
  'SettingsTimeFormat12': undefined;
  'SettingsTimeFormat24': undefined;
  'SettingsKeyboard': undefined;
  'SettingsTray': undefined;
  'SettingsOfflineNotificationUnsupported': undefined;
  'TextSize': undefined;
  'ChatBackground': undefined;
  'Theme': undefined;
  'AccDescrStickers': undefined;
  'DoubleTapSetting': undefined;
  'SuggestStickers': undefined;
  'LoopAnimatedStickers': undefined;
  'UploadImage': undefined;
  'SetColor': undefined;
  'ThemeResetToDefaults': undefined;
  'BackgroundBlurred': undefined;
  'SettingsInformation': undefined;
  'General': undefined;
  'DataSettings': undefined;
  'PrivacySettings': undefined;
  'Language': undefined;
  'SettingsExperimental': undefined;
  'PrivacyPhone': undefined;
  'PrivacyLastSeen': undefined;
  'PrivacyProfilePhoto': undefined;
  'PrivacyForwards': undefined;
  'AutodownloadGroupChats': undefined;
  'AlwaysShareWith': undefined;
  'NeverShareWith': undefined;
  'SessionsTitle': undefined;
  'SessionTerminate': undefined;
  'OtherWebSessions': undefined;
  'BlockedUsers': undefined;
  'TwoStepVerification': undefined;
  'PleaseEnterCurrentPassword': undefined;
  'PleaseReEnterPassword': undefined;
  'PasswordHint': undefined;
  'RecoveryEmailTitle': undefined;
  'TwoStepVerificationPasswordSet': undefined;
  'Passcode': undefined;
  'PasscodeControllerDisableTitle': undefined;
  'PasscodeControllerChangeTitle': undefined;
  'FilterNew': undefined;
  'EditFolder': undefined;
  'FilterEditFolders': undefined;
  'FilterMenuDelete': undefined;
  'FilterShare': undefined;
  'AutoDeleteConfirm': undefined;
  'LogOutTitle': undefined;
  'AccDescrGoBack': undefined;
  'SureLogout': undefined;
  'AccountSettingsLogout': undefined;
  'TelegramGeneralSettingsViewController': undefined;
  'UserInfoNotificationsEnabled': undefined;
  'UserInfoNotificationsDisabled': undefined;
  'AutodownloadPrivateChats': undefined;
  'NotificationsForPrivateChats': undefined;
  'MessagePreview': undefined;
  'FilterGroups': undefined;
  'NotificationsForGroups': undefined;
  'FilterChannels': undefined;
  'NotificationsForChannels': undefined;
  'PhoneOther': undefined;
  'ContactJoined': undefined;
  'P2PEverybody': undefined;
  'P2PContacts': undefined;
  'P2PNobody': undefined;
  'PrivacySettingsWebSessions': undefined;
  'PrivacyTitle': undefined;
  'PrivacyPhoneTitle': undefined;
  'LastSeenTitle': undefined;
  'PrivacyProfilePhotoTitle': undefined;
  'WhoCanCallMe': undefined;
  'PrivacyP2P': undefined;
  'PrivacyForwardsTitle': undefined;
  'WhoCanAddMe': undefined;
  'NewChatsFromNonContacts': undefined;
  'ArchiveAndMute': undefined;
  'ArchiveAndMuteInfo': undefined;
  'SettingsSensitiveTitle': undefined;
  'SettingsSensitiveDisableFiltering': undefined;
  'SettingsSensitiveAbout': undefined;
  'BlockedUsersInfo': undefined;
  'NoBlocked': undefined;
  'BlockContact': undefined;
  'CustomHelp': undefined;
  'PrivacyExceptions': undefined;
  'AlwaysAllow': undefined;
  'EditAdminAddUsers': undefined;
  'NeverAllow': undefined;
  'AlwaysAllowPlaceholder': undefined;
  'NeverAllowPlaceholder': undefined;
  'PleaseEnterPassword': undefined;
  'PasswordHintPlaceholder': undefined;
  'TwoStepVerificationPasswordSetInfo': undefined;
  'TwoStepVerificationPasswordReturnSettings': undefined;
  'YourEmailCode': undefined;
  'EnabledPasswordText': undefined;
  'ChangePassword': undefined;
  'TurnPasswordOff': undefined;
  'SetRecoveryEmail': undefined;
  'YourEmailSkip': undefined;
  'YourEmailSkipWarning': undefined;
  'YourEmailSkipWarningText': undefined;
  'SetAdditionalPasswordInfo': undefined;
  'EditAdminTransferSetPassword': undefined;
  'BotOpenPageTitle': undefined;
  'FilterDeleteAlert': undefined;
  'RequestToJoinChannelSentDescription': undefined;
  'RequestToJoinGroupSentDescription': undefined;
  'ChannelJoin': undefined;
  'JoinGroup': undefined;
  'MemberRequestsRequestToJoinChannel': undefined;
  'MemberRequestsRequestToJoinGroup': undefined;
  'MemberRequestsRequestToJoinDescriptionChannel': undefined;
  'MemberRequestsRequestToJoinDescriptionGroup': undefined;
  'ShareYouPhoneNumberTitle': undefined;
  'AreYouSureShareMyContactInfoBot': undefined;
  'ContactShare': undefined;
  'OK': undefined;
  'ForwardTo': undefined;
  'AttachGame': undefined;
  'JumpToDate': undefined;
  'FloodWait': undefined;
  'PasscodeWrong': undefined;
  'PasscodeEnterPasscodePlaceholder': undefined;
  'MobileHidden': undefined;
  'NewContactShare': undefined;
  'ContactPhone': undefined;
  'NewContact': undefined;
  'Done': undefined;
  'LimitReached': undefined;
  'IncreaseLimit': undefined;
  'LimitFree': undefined;
  'LimitPremium': undefined;
  'TelegramPremiumSubscribedTitle': undefined;
  'AboutPremiumDescription': undefined;
  'AboutPremiumDescription2': undefined;
  'OpenUrlTitle': undefined;
  'OpenUrlConfirm': undefined;
  'BotWebViewOpenBot': undefined;
  'BotChatMiniAppOpen': undefined;
  'WebAppReloadPage': undefined;
  'WebAppRemoveBot': undefined;
  'WebAppAddToAttachmentAdd': undefined;
  'AccActionDownload': undefined;
  'Forward': undefined;
  'MediaZoomOut': undefined;
  'MediaZoomIn': undefined;
  'PeerInfoReportProfileVideo': undefined;
  'PeerInfoReportProfilePhoto': undefined;
  'MediaviewProfilePhoto': undefined;
  'AccActionPlay': undefined;
  'AttachAudio': undefined;
  'NewContactAdd': undefined;
  'NewContactBlock': undefined;
  'ReportSpamAndLeave': undefined;
  'ChatConfirmReportSpamChannel': undefined;
  'Block': undefined;
  'DeleteThisChat': undefined;
  'Caption': undefined;
  'CropperTitle': undefined;
  'CropperApply': undefined;
  'AttachmentMenuPhotoOrVideo': undefined;
  'AttachDocument': undefined;
  'Poll': undefined;
  'SendMessageAsTitle': undefined;
  'Message': undefined;
  'RecentStickers': undefined;
  'PollsChooseQuestion': undefined;
  'PollsChooseAnswers': undefined;
  'NewPoll': undefined;
  'Create': undefined;
  'OptionHint': undefined;
  'CreatePollAddOption': undefined;
  'PollsChooseCorrect': undefined;
  'AskAQuestion': undefined;
  'PollOptions': undefined;
  'PollAnonymous': undefined;
  'PollMultiple': undefined;
  'PollQuiz': undefined;
  'PollsSolutionTitle': undefined;
  'CreatePollExplanationInfo': undefined;
  'VoipGroupPersonalAccount': undefined;
  'MenuStickers': undefined;
  'MenuAnimations': undefined;
  'MenuStars': undefined;
  'MenuTon': undefined;
  'MenuSendGift': undefined;
  'MenuTelegramFaq': undefined;
  'MenuPrivacyPolicy': undefined;
  'MenuAskText': undefined;
  'SettingsPerformanceSliderTitle': undefined;
  'SettingsPerformanceSliderSubtitle': undefined;
  'SettingsPerformanceSliderLow': undefined;
  'SettingsPerformanceSliderMedium': undefined;
  'SettingsPerformanceSliderCustom': undefined;
  'SettingsPerformanceSliderHigh': undefined;
  'SettingsPerformanceInterfaceAnimations': undefined;
  'SettingsPerformanceStickers': undefined;
  'SettingsPerformanceMediaAutoplay': undefined;
  'SettingsPerformancePageTransitions': undefined;
  'SettingsPerformanceSending': undefined;
  'SettingsPerformanceMediaViewer': undefined;
  'SettingsPerformanceComposer': undefined;
  'SettingsPerformanceContextAnimation': undefined;
  'SettingsPerformanceContextBlur': undefined;
  'SettingsPerformanceRightColumn': undefined;
  'SettingsPerformanceThanos': undefined;
  'SettingsPerformanceAnimatedEmoji': undefined;
  'SettingsPerformanceLoopStickers': undefined;
  'SettingsPerformanceReactionEffects': undefined;
  'SettingsPerformanceStickerEffects': undefined;
  'SettingsPerformanceAutoplayGif': undefined;
  'SettingsPerformanceAutoplayVideo': undefined;
  'SettingsPerformanceGranularTitle': undefined;
  'FavoriteStickers': undefined;
  'PremiumStickers': undefined;
  'GroupStickers': undefined;
  'ErrorSendRestrictedStickersAll': undefined;
  'ErrorPhoneNumberInvalid': undefined;
  'ErrorCodeInvalid': undefined;
  'ErrorEmailCodeInvalid': undefined;
  'ErrorIncorrectPassword': undefined;
  'ErrorPasswordFlood': undefined;
  'ErrorPhoneBanned': undefined;
  'ErrorUnexpected': undefined;
  'ErrorEmailUnconfirmed': undefined;
  'ErrorEmailHashExpired': undefined;
  'ErrorNewSaltInvalid': undefined;
  'ErrorPasswordChanged': undefined;
  'ErrorPasswordMissing': undefined;
  'ErrorPasskeyUnknown': undefined;
  'ErrorUnspecified': undefined;
  'NoStickers': undefined;
  'ClearRecentEmoji': undefined;
  'Save': undefined;
  'ConversationEmptyPlaceholder': undefined;
  'ConversationGreetingText': undefined;
  'ConversationDeleteManyMessages': undefined;
  'AreYouSureDeleteFewMessages': undefined;
  'ProfileJoinChannel': undefined;
  'ProfileJoinGroup': undefined;
  'ChannelJoinRequest': undefined;
  'BotStart': undefined;
  'BotRestart': undefined;
  'SubscribeRequests': undefined;
  'MemberRequests': undefined;
  'AddContact': undefined;
  'Call': undefined;
  'VideoCall': undefined;
  'ChatsUnmute': undefined;
  'ChatsMute': undefined;
  'StartVoipChat': undefined;
  'VoipGroupJoinCall': undefined;
  'ViewDiscussion': undefined;
  'ProfileViewChannel': undefined;
  'ReportSelectMessages': undefined;
  'Statistics': undefined;
  'EventLogFilterPinnedMessages': undefined;
  'UnpinMessageAlertTitle': undefined;
  'PinnedMessageTitleSingle': undefined;
  'AccPinnedMessages': undefined;
  'AccUnpinMessage': undefined;
  'LeaveAComment': undefined;
  'PollsStopWarning': undefined;
  'PollsStopSure': undefined;
  'PaymentTestInvoice': undefined;
  'PaymentInvoiceNotFound': undefined;
  'NoWordsRecognized': undefined;
  'ViaBot': undefined;
  'DiscussChannel': undefined;
  'ForwardedMessage': undefined;
  'ContextForwardMsg': undefined;
  'MessageScheduleSend': undefined;
  'MessageScheduleEditTime': undefined;
  'Reply': undefined;
  'Edit': undefined;
  'AddToFavorites': undefined;
  'ContextSaveGif': undefined;
  'PollsRetract': undefined;
  'PollsStop': undefined;
  'ContextCancelDownload': undefined;
  'MediaDownload': undefined;
  'CommonSelect': undefined;
  'ContextReportMsg': undefined;
  'ConversationContextMenuNoViews': undefined;
  'HideAd': undefined;
  'EditedMessage': undefined;
  'CallAgain': undefined;
  'CallBack': undefined;
  'PollSubmitVotes': undefined;
  'PollViewResults': undefined;
  'ChatQuizTotalVotesEmpty': undefined;
  'ChatPollTotalVotesResultEmpty': undefined;
  'Vote': undefined;
  'MessageRecommendedLabel': undefined;
  'SponsoredMessageAd': undefined;
  'SponsoredMessageAdWhatIsThis': undefined;
  'SponsoredPeerBadge': undefined;
  'PremiumStickerTooltip': undefined;
  'ViewAction': undefined;
  'Loading': undefined;
  'NoMessages': undefined;
  'BotInfoTitle': undefined;
  'UnreadMessages': undefined;
  'DiscussionStarted': undefined;
  'MessageScheduledUntilOnline': undefined;
  'ChatForwardActionHeader': undefined;
  'ConversationReportMessages': undefined;
  'ContextCopySelectedItems': undefined;
  'EditAdminGroupDeleteMessages': undefined;
  'Reminders': undefined;
  'MessageMetaEdited': undefined;
  'MessageMetaApproximate': undefined;
  'MessageMetaImported': undefined;
  'ImportedInfo': undefined;
  'ScheduledMessagesEmptyPlaceholder': undefined;
  'ConversationCloudStorageInfoTitle': undefined;
  'ConversationClousStorageInfoDescription1': undefined;
  'ConversationClousStorageInfoDescription2': undefined;
  'ConversationClousStorageInfoDescription3': undefined;
  'ConversationClousStorageInfoDescription4': undefined;
  'EmptyGroupInfoTitle': undefined;
  'EmptyGroupInfoSubtitle': undefined;
  'EmptyGroupInfoLine2': undefined;
  'EmptyGroupInfoLine3': undefined;
  'EmptyGroupInfoLine4': undefined;
  'Reactions': undefined;
  'ChatListMarkAllAsRead': undefined;
  'PaymentCardNumber': undefined;
  'CheckoutTotalAmount': undefined;
  'PaymentCheckoutMethod': undefined;
  'PaymentCheckoutProvider': undefined;
  'PaymentShippingAddress': undefined;
  'PaymentCheckoutName': undefined;
  'PaymentCheckoutPhoneNumber': undefined;
  'PaymentCheckoutShippingMethod': undefined;
  'CheckoutWebConfirmationTitle': undefined;
  'PaymentCardExpireDate': undefined;
  'PaymentCardTitle': undefined;
  'CheckoutNewCardCardholderNamePlaceholder': undefined;
  'PaymentsCardCvc': undefined;
  'PaymentBillingAddress': undefined;
  'PaymentShippingCountry': undefined;
  'PaymentShippingZipPlaceholder': undefined;
  'PaymentCardSavePaymentInformation': undefined;
  'PaymentShippingInfo': undefined;
  'PaymentShippingMethod': undefined;
  'PaymentCardInfo': undefined;
  'PaymentCheckout': undefined;
  'PaymentReceipt': undefined;
  'PaymentShippingAddress1Placeholder': undefined;
  'PaymentShippingAddress2Placeholder': undefined;
  'PaymentShippingCityPlaceholder': undefined;
  'PaymentShippingStatePlaceholder': undefined;
  'PaymentShippingReceiver': undefined;
  'PaymentShippingName': undefined;
  'PaymentShippingEmailPlaceholder': undefined;
  'PaymentShippingPhoneNumber': undefined;
  'PaymentShippingSave': undefined;
  'PaymentShippingSaveInfo': undefined;
  'ChannelAddUsers': undefined;
  'GroupRemovedRemove': undefined;
  'BoxRemove': undefined;
  'NoGIFsFound': undefined;
  'ChannelAddToChannel': undefined;
  'ChannelAddToGroup': undefined;
  'DismissRequest': undefined;
  'DescriptionPlaceholder': undefined;
  'TypePublic': undefined;
  'TypePrivate': undefined;
  'Discussion': undefined;
  'DiscussionUnlink': undefined;
  'GroupInfoInviteLinks': undefined;
  'ChannelSignMessages': undefined;
  'ChannelAdministrators': undefined;
  'ChannelSubscribers': undefined;
  'ChannelBlockedUsers': undefined;
  'ChannelDelete': undefined;
  'ChannelLeave': undefined;
  'ChannelDeleteAlert': undefined;
  'ChannelLeaveAlert': undefined;
  'ChannelCreator': undefined;
  'ChannelAdmin': undefined;
  'EventLog': undefined;
  'EventLogInfoDetailChannel': undefined;
  'EventLogInfoDetail': undefined;
  'ChannelManagementAddModerator': undefined;
  'ChannelVisibilityForwardingEnabled': undefined;
  'ChannelVisibilityForwardingDisabled': undefined;
  'RevokeLink': undefined;
  'RevokeAlert': undefined;
  'RevokeButton': undefined;
  'ChannelVisibilityForwardingChannelTitle': undefined;
  'ChannelVisibilityForwardingGroupTitle': undefined;
  'ChannelVisibilityForwardingChannelInfo': undefined;
  'ChannelVisibilityForwardingGroupInfo': undefined;
  'Unblock': undefined;
  'NoBlockedChannel2': undefined;
  'NoBlockedGroup2': undefined;
  'ChannelEditAdminPermissionBanUsers': undefined;
  'DiscussionUnlinkGroup': undefined;
  'DiscussionUnlinkChannel': undefined;
  'ChannelDiscussionGroupLinkGroup': undefined;
  'DiscussionChannelHelp': undefined;
  'DiscussionCreateGroup': undefined;
  'DiscussionChannelHelp2': undefined;
  'DiscussionLinkGroup': undefined;
  'ChannelSettingsJoinTitle': undefined;
  'ChannelSettingsJoinToSend': undefined;
  'ChannelSettingsJoinRequest': undefined;
  'ChannelSettingsJoinRequestInfo': undefined;
  'ChannelSettingsJoinToSendInfo': undefined;
  'LinkedChannel': undefined;
  'ChannelPermissions': undefined;
  'GroupMembers': undefined;
  'ChatHistory': undefined;
  'DeleteMega': undefined;
  'AreYouSureDeleteAndExit': undefined;
  'DeleteGroupForAll': undefined;
  'EditAdminWhatCanDo': undefined;
  'EditAdminChangeChannelInfo': undefined;
  'EditAdminChangeGroupInfo': undefined;
  'EditAdminPostMessages': undefined;
  'EditAdminEditMessages': undefined;
  'EditAdminDeleteMessages': undefined;
  'EditAdminBanUsers': undefined;
  'EditAdminPinMessages': undefined;
  'EditAdminAddAdmins': undefined;
  'StartVoipChatPermission': undefined;
  'EditAdminSendAnonymously': undefined;
  'ChannelEditAdminCannotEdit': undefined;
  'EditAdminRank': undefined;
  'EditAdminRemoveAdmin': undefined;
  'ChannelAdminDismiss': undefined;
  'ChannelPermissionsHeader': undefined;
  'UserRestrictionsSend': undefined;
  'UserRestrictionsSendMedia': undefined;
  'UserRestrictionsCreateTopics': undefined;
  'SendMediaPermissionFiles': undefined;
  'SendMediaPermissionPhotos': undefined;
  'SendMediaPermissionVideos': undefined;
  'SendMediaPermissionStickersGifs': undefined;
  'SendMediaPermissionAudios': undefined;
  'SendMediaPermissionVoices': undefined;
  'SendMediaPermissionRoundVideos': undefined;
  'SendMediaPermissionWebPages': undefined;
  'SendMediaPermissionPolls': undefined;
  'UserRestrictionsEmbedLinks': undefined;
  'UserRestrictionsChangeInfo': undefined;
  'ChannelAddException': undefined;
  'EventLogAllEvents': undefined;
  'EventLogFilterNewAdmins': undefined;
  'EventLogFilterNewMembers': undefined;
  'EventLogFilterChannelInfo': undefined;
  'EventLogFilterDeletedMessages': undefined;
  'EventLogFilterEditedMessages': undefined;
  'EventLogFilterLeavingMembers': undefined;
  'ChannelManagementTitle': undefined;
  'MyProfileHeader': undefined;
  'EventLogAllAdmins': undefined;
  'UserRestrictionsCanDo': undefined;
  'UserRestrictionsBlock': undefined;
  'ApproveNewMembers': undefined;
  'ApproveNewMembersDescription': undefined;
  'LinkNameHint': undefined;
  'LinkNameHelp': undefined;
  'LimitByPeriod': undefined;
  'NoLimit': undefined;
  'GroupInviteExpireCustom': undefined;
  'TimeLimitHelp': undefined;
  'LimitNumberOfUses': undefined;
  'GroupInviteUsageCustom': undefined;
  'UsesLimitHelp': undefined;
  'SaveLink': undefined;
  'CreateLink': undefined;
  'LinkCopied': undefined;
  'NoOneJoined': undefined;
  'NoOneJoinedYet': undefined;
  'CopyLink': undefined;
  'ExpiredLink': undefined;
  'LinkCreatedeBy': undefined;
  'Revoked': undefined;
  'LinkLimitReached': undefined;
  'InviteLinkExpired': undefined;
  'Permanent': undefined;
  'DeleteLink': undefined;
  'PrimaryLinkHelpChannel': undefined;
  'PrimaryLinkHelp': undefined;
  'PublicLink': undefined;
  'CreatePermanentLinkTitle': undefined;
  'CreateNewLink': undefined;
  'ManageLinksInfoHelp': undefined;
  'RevokedLinks': undefined;
  'DeleteAllRevokedLinks': undefined;
  'DeleteAllRevokedLinkHelp': undefined;
  'DeleteAll': undefined;
  'DeleteLinkHelp': undefined;
  'NoMemberRequests': undefined;
  'NoSubscribeRequestsDescription': undefined;
  'NoMemberRequestsDescription': undefined;
  'EnableReactions': undefined;
  'UserInfoFirstNamePlaceholder': undefined;
  'UserInfoLastNamePlaceholder': undefined;
  'DeleteContact': undefined;
  'AreYouSureDeleteContact': undefined;
  'ChannelBlockUser': undefined;
  'ContextRemoveFromGroup': undefined;
  'NoGroupsInCommon': undefined;
  'MediaFileEmpty': undefined;
  'MediaLinkEmpty': undefined;
  'MediaSongEmpty': undefined;
  'MediaAudioEmpty': undefined;
  'SharedMediaEmptyTitle': undefined;
  'PollResults': undefined;
  'ChannelAddSubscribers': undefined;
  'ChannelTypeHeader': undefined;
  'GroupTypeHeader': undefined;
  'GroupInfoAdminLog': undefined;
  'EditAdminRights': undefined;
  'SetAsAdmin': undefined;
  'UserRestrictions': undefined;
  'GroupInviteTitle': undefined;
  'EditLink': undefined;
  'NewLink': undefined;
  'InviteLink': undefined;
  'SearchStickersHint': undefined;
  'SearchGifsTitle': undefined;
  'ChannelStatsTitle': undefined;
  'GroupStatsTitle': undefined;
  'StatsMessageTitle': undefined;
  'SharedMedia': undefined;
  'CommonBack': undefined;
  'CommonClose': undefined;
  'DlgSearchForMessages': undefined;
  'SearchNoResults': undefined;
  'GraphZoomOut': undefined;
  'ChannelStatsRecentHeader': undefined;
  'StatisticOverview': undefined;
  'Stickers': undefined;
  'StickersInstalled': undefined;
  'StickersInstall': undefined;
  'CropImage': undefined;
  'ReportPeerAlertSuccess': undefined;
  'WebAppAddToAttachmentUnavailableError': undefined;
  'LimitReachedFavoriteGifsSubtitlePremium': undefined;
  'LimitReachedFavoriteStickersSubtitlePremium': undefined;
  'StickerPackErrorNotFound': undefined;
  'ContactsPhoneNumberNotRegistred': undefined;
  'NoUsernameFound': undefined;
  'PrivateChannelInaccessible': undefined;
  'HiddenName': undefined;
  'ChannelPersmissionDeniedSendMessagesForever': undefined;
  'ChannelPersmissionDeniedSendMessagesDefaultRestrictedText': undefined;
  'Chats': undefined;
  'FilterBots': undefined;
  'FilterContacts': undefined;
  'FilterNonContacts': undefined;
  'FromYou': undefined;
  'Album': undefined;
  'AttachPhoto': undefined;
  'AttachGif': undefined;
  'AttachVideo': undefined;
  'AttachSticker': undefined;
  'AttachMusic': undefined;
  'AttachContact': undefined;
  'AttachStory': undefined;
  'AttachLocation': undefined;
  'AttachLiveLocation': undefined;
  'AttachGiveaway': undefined;
  'AttachGiveawayResults': undefined;
  'AttachTodo': undefined;
  'ServiceNotifications': undefined;
  'Bot': undefined;
  'ALongTimeAgo': undefined;
  'WithinAMonth': undefined;
  'WithinAWeek': undefined;
  'LastSeenOffline': undefined;
  'LastSeenJustNow': undefined;
  'Online': undefined;
  'Lately': undefined;
  'VoipMutedTapedForSpeak': undefined;
  'VoipMutedByAdmin': undefined;
  'VoipUnmute': undefined;
  'VoipTapToMute': undefined;
  'Weekday1': undefined;
  'Weekday2': undefined;
  'Weekday3': undefined;
  'Weekday4': undefined;
  'Weekday5': undefined;
  'Weekday6': undefined;
  'Weekday7': undefined;
  'WeekdayMonday': undefined;
  'WeekdayTuesday': undefined;
  'WeekdayWednesday': undefined;
  'WeekdayThursday': undefined;
  'WeekdayFriday': undefined;
  'WeekdaySaturday': undefined;
  'WeekdaySunday': undefined;
  'WeekdayToday': undefined;
  'Today': undefined;
  'WeekdayYesterday': undefined;
  'User': undefined;
  'SecretChat': undefined;
  'MessageRepeatPeriodDaily': undefined;
  'MessageRepeatPeriodWeekly': undefined;
  'MessageRepeatPeriodBiweekly': undefined;
  'MessageRepeatPeriodMonthly': undefined;
  'MessageRepeatPeriodYearly': undefined;
  'MessageScheduledRepeatPremium': undefined;
  'ChatListFilterErrorEmpty': undefined;
  'ChatListFilterErrorTitleEmpty': undefined;
  'FilterMuted': undefined;
  'FilterRead': undefined;
  'FilterArchived': undefined;
  'GroupsAndChannelsLimitTitle': undefined;
  'PinChatsLimitTitle': undefined;
  'PublicLinksLimitTitle': undefined;
  'SavedGifsLimitTitle': undefined;
  'FavoriteStickersLimitTitle': undefined;
  'BioLimitTitle': undefined;
  'CaptionsLimitTitle': undefined;
  'FoldersLimitTitle': undefined;
  'ChatPerFolderLimitTitle': undefined;
  'BioLimitSubtitle': undefined;
  'CaptionsLimitSubtitle': undefined;
  'TelegramPremiumUserDialogSubtitle': undefined;
  'TelegramPremiumSubscribedSubtitle': undefined;
  'TelegramPremiumSubtitle': undefined;
  'EditMessageAriaLabel': undefined;
  'Emoji1': undefined;
  'Emoji2': undefined;
  'Emoji3': undefined;
  'Emoji4': undefined;
  'Emoji5': undefined;
  'Emoji6': undefined;
  'Emoji7': undefined;
  'Emoji8': undefined;
  'GroupInfoDeleteAndExit': undefined;
  'HidAccount': undefined;
  'ConversationViewBot': undefined;
  'ConversationViewPost': undefined;
  'ConversationViewChannel': undefined;
  'Telegram': undefined;
  'ChatListFilterAddToFolder': undefined;
  'ChatListUnpinFromTop': undefined;
  'ChatListPinToTop': undefined;
  'ChatListOpenInNewWindow': undefined;
  'ChatListOpenInNewTab': undefined;
  'ChatListContextMaskAsRead': undefined;
  'ChatListContextMaskAsUnread': undefined;
  'ChatListContextAddToFolder': undefined;
  'Unarchive': undefined;
  'Archive': undefined;
  'WaitingForNetwork': undefined;
  'ScheduleSendWhenOnline': undefined;
  'ScheduleRepeatNever': undefined;
  'ScheduleRepeatDaily': undefined;
  'ScheduleRepeatWeekly': undefined;
  'ScheduleRepeatBiweekly': undefined;
  'ScheduleRepeatMonthly': undefined;
  'ScheduleRepeatYearly': undefined;
  'VoipIncoming': undefined;
  'LiveLocationUpdatedJustNow': undefined;
  'RightNow': undefined;
  'JustNowAgo': undefined;
  'AudioPause': undefined;
  'AudioPlay': undefined;
  'AriaToggleUserNotifications': undefined;
  'AriaToggleChatNotifications': undefined;
  'ChannelInaccessible': undefined;
  'GroupInaccessible': undefined;
  'AriaPasswordToggle': undefined;
  'NothingFound': undefined;
  'SetUrlShort': undefined;
  'SetUrlLong': undefined;
  'SetUrlInvalid': undefined;
  'UsernameShort': undefined;
  'UsernameLong': undefined;
  'UsernameInvalid': undefined;
  'AriaCodeWordWrap': undefined;
  'AriaBackToChatList': undefined;
  'NoContactsFound': undefined;
  'ContactListEmpty': undefined;
  'AriaNewChannelContinue': undefined;
  'AriaNewGroupContinue': undefined;
  'NewChatTitleEmptyError': undefined;
  'NewChannelTitleEmptyError': undefined;
  'NewChatTooManyUsers': undefined;
  'AriaCreateGroup': undefined;
  'SearchAllMessagesTab': undefined;
  'SearchMediaTab': undefined;
  'SearchLinksTab': undefined;
  'SearchGifsTab': undefined;
  'SearchFilesTab': undefined;
  'SearchMusicTab': undefined;
  'SearchVoiceTab': undefined;
  'SearchGroupsTab': undefined;
  'RecentChatsClear': undefined;
  'EditProfileNoFirstName': undefined;
  'AriaEditProfilePhoto': undefined;
  'LaunchConfetti': undefined;
  'AriaMoreButton': undefined;
  'RecoveryEmailCode': undefined;
  'NotificationsWeb': undefined;
  'NotificationsOffline': undefined;
  'NotificationsSound': undefined;
  'SettingsPasswordEqual': undefined;
  'SettingsSaveChanges': undefined;
  'SettingsFolderCreate': undefined;
  'SettingsFoldersEmpty': undefined;
  'SettingsPasscodeSuccess': undefined;
  'SettingsPasscodeEnabled': undefined;
  'SettingsPasscodeStart1': undefined;
  'SettingsPasscodeStart2': undefined;
  'CurrentPasswordPlaceholder': undefined;
  'ChangeYourProfilePicture': undefined;
  'AppInactiveOtherClientTitle': undefined;
  'AppInactiveOtherClientDescription': undefined;
  'AppInactiveAuthTitle': undefined;
  'AppInactiveAuthDescription': undefined;
  'AppInactiveReload': undefined;
  'SlowmodeEnabled': undefined;
  'SomethingWentWrong': undefined;
  'VideoPlayerBuffering': undefined;
  'VideoPlayerFullscreen': undefined;
  'PlayerVolume': undefined;
  'PlayerPlaybackRate': undefined;
  'AudioPlayerPrevious': undefined;
  'AudioPlayerNext': undefined;
  'AudioPlayerClose': undefined;
  'DeleteForMeDescription': undefined;
  'DeleteForEveryoneDescription': undefined;
  'AriaSearchInChat': undefined;
  'PinnedConfirmUnpin': undefined;
  'RestictionReasonPrivateChat': undefined;
  'RestictionReasonPrivateChannel': undefined;
  'BotInfoImageAlt': undefined;
  'AriaExitMessageSelection': undefined;
  'AriaSearchByDate': undefined;
  'AriaCloseAttachmentModal': undefined;
  'AriaAddAttachment': undefined;
  'AttachMenuMediaBlocked': undefined;
  'AriaOpenBotMenu': undefined;
  'AriaOpenSymbolMenu': undefined;
  'AriaComposerOpenScheduled': undefined;
  'AriaComposerBotKeyboard': undefined;
  'AriaComposerSilentPostingEnable': undefined;
  'AriaComposerSilentPostingDisable': undefined;
  'ComposerSilentPostingEnabledTootlip': undefined;
  'ComposerSilentPostingDisabledTootlip': undefined;
  'ComposerPlaceholder': undefined;
  'ComposerPlaceholderAnonymous': undefined;
  'ComposerPlaceholderBroadcast': undefined;
  'ComposerPlaceholderBroadcastSilent': undefined;
  'ComposerPlaceholderTopicGeneral': undefined;
  'ComposerStoryPlaceholderLocked': undefined;
  'ComposerPlaceholderNoText': undefined;
  'AriaComposerCancelVoice': undefined;
  'PreviewEditMessage': undefined;
  'FileDropZoneTitle': undefined;
  'FileDropZoneQuick': undefined;
  'FileDropZoneNoCompression': undefined;
  'GifPickerBlocked': undefined;
  'GifPickerEmpty': undefined;
  'AriaCancelPollCreation': undefined;
  'AriaLabelSearchStickers': undefined;
  'AriaLabelSearchGifs': undefined;
  'FormattingSpoilerAria': undefined;
  'FormattingBoldAria': undefined;
  'FormattingItalicAria': undefined;
  'FormattingMonospaceAria': undefined;
  'FormattingUnderlineAria': undefined;
  'FormattingStrikethroughAria': undefined;
  'FormattingAddLinkAria': undefined;
  'FormattingEnterUrl': undefined;
  'PreviewWebPageClose': undefined;
  'MediaLocaltionImageAlt': undefined;
  'MediaPollSolutionAria': undefined;
  'GeneralError': undefined;
  'PaymentsProvidesNotSupported': undefined;
  'ChatMemberListNoAccess': undefined;
  'NoMembersFound': undefined;
  'Profile': undefined;
  'ChannelManagementAddAdminDescription': undefined;
  'GroupManagementAddAdminDescription': undefined;
  'ChannelManagementLinkPrivate': undefined;
  'NoDiscussionsLinked': undefined;
  'ManagementRemoveAdminConfirm': undefined;
  'NoSubscribersFound': undefined;
  'GroupManagementBanUserConfirm': undefined;
  'NoLinksFound': undefined;
  'JoinRequestAcceptAllTitle': undefined;
  'JoinRequestAcceptAllDescription': undefined;
  'JoinRequestRejectAllTitle': undefined;
  'JoinRequestRejectAllDescription': undefined;
  'StatsNoShares': undefined;
  'AvatarChangeTitle': undefined;
  'PleaseWait': undefined;
  'GeneralConfirm': undefined;
  'ImageCropTitle': undefined;
  'NewChatReturnBackAria': undefined;
  'FoldersAllChatsDesc': undefined;
  'RemoveSymbol': undefined;
  'FocusMessage': undefined;
  'HiddenSendersNameDescription': undefined;
  'ShowSenderNames': undefined;
  'ShowSendersName': undefined;
  'HideSenderNames': undefined;
  'HideSendersName': undefined;
  'ConversationForwardOptionsShowCaption': undefined;
  'ShowCaption': undefined;
  'ConversationForwardOptionsHideCaption': undefined;
  'HideCaption': undefined;
  'ChangeRecipient': undefined;
  'DragToSortAria': undefined;
  'MenuReportBug': undefined;
  'MenuBetaChangelog': undefined;
  'MenuSwitchToK': undefined;
  'MenuInstallApp': undefined;
  'MenuMyProfile': undefined;
  'MenuSavedMessages': undefined;
  'MenuArchivedChats': undefined;
  'MenuContacts': undefined;
  'MenuSettings': undefined;
  'MenuNightMode': undefined;
  'AriaMenuEnableNightMode': undefined;
  'AriaMenuDisableNightMode': undefined;
  'AriaSettingsEditProfilePhoto': undefined;
  'MenuAnimationsSwitch': undefined;
  'MenuTelegramFeatures': undefined;
  'TelegramFeaturesUsername': undefined;
  'RemoveEffect': undefined;
  'ReplyInPrivateMessage': undefined;
  'ProfileOpenAppTerms': undefined;
  'ProfileBotOpenAppInfoLink': undefined;
  'ProfileBirthday': undefined;
  'ProfileBirthdayToday': undefined;
  'ProfileMenuSetMainTab': undefined;
  'ProfileItemSubscribers': undefined;
  'MonetizationInfoTONTitle': undefined;
  'AriaSearchOlderResult': undefined;
  'AriaSearchNewerResult': undefined;
  'StarsTransactionTOSLinkText': undefined;
  'StarsTransactionTOSLink': undefined;
  'GiftPremiumHeader': undefined;
  'GiftPremiumDescriptionLinkCaption': undefined;
  'GiftPremiumDescriptionLink': undefined;
  'StarsGiftHeader': undefined;
  'StarsGiftHeaderSelf': undefined;
  'StarGiftDescriptionCollectibles': undefined;
  'StarGiftDescriptionSelf': undefined;
  'GiftLimited': undefined;
  'GiftSoldOut': undefined;
  'GiftMessagePlaceholder': undefined;
  'GiftHideMyName': undefined;
  'GiftHideNameDescriptionSelf': undefined;
  'GiftHideNameDescriptionChannel': undefined;
  'GiftInfoSent': undefined;
  'GiftInfoReceived': undefined;
  'GiftInfoTitle': undefined;
  'GiftInfoDescriptionRegular': undefined;
  'GiftInfoDescriptionUpgradeRegular': undefined;
  'GiftInfoDescriptionFreeUpgrade': undefined;
  'GiftInfoDescriptionUpgrade2': undefined;
  'GiftInfoDescriptionUpgraded': undefined;
  'GiftInfoDescriptionRefunded': undefined;
  'GiftInfoFrom': undefined;
  'GiftInfoDate': undefined;
  'GiftInfoValue': undefined;
  'GiftInfoConvertTitle': undefined;
  'GiftInfoConvertDescription2': undefined;
  'GiftInfoSavedHide': undefined;
  'GiftInfoSavedShow': undefined;
  'GiftActionShow': undefined;
  'GiftActionHide': undefined;
  'GiftInfoTonLinkText': undefined;
  'GiftInfoAvailability': undefined;
  'GiftInfoValueLinkMore': undefined;
  'GiftInfoFirstSale': undefined;
  'GiftInfoLastSale': undefined;
  'GiftValueTitleInitialSale': undefined;
  'GiftValueTitleInitialPrice': undefined;
  'GiftValueTitleLastSale': undefined;
  'GiftValueTitleLastPrice': undefined;
  'GiftValueTitleMinimumPrice': undefined;
  'GiftValueTitleAveragePrice': undefined;
  'GiftInfoSoldOutTitle': undefined;
  'GiftInfoSoldOutDescription': undefined;
  'GiftInfoSenderHidden': undefined;
  'GiftInfoOwner': undefined;
  'GiftAttributeModel': undefined;
  'GiftAttributeBackdrop': undefined;
  'GiftAttributeSymbol': undefined;
  'GiftInfoStatus': undefined;
  'GiftInfoStatusNonUnique': undefined;
  'GiftInfoViewUpgraded': undefined;
  'GiftInfoUpgradeBadge': undefined;
  'GiftInfoUpgradeForFree': undefined;
  'GiftInfoUpgrade': undefined;
  'GiftInfoWithdraw': undefined;
  'GiftInfoWear': undefined;
  'GiftInfoTakeOff': undefined;
  'GiftInfoTransfer': undefined;
  'GiftInfoUnlist': undefined;
  'GiftTransferTitle': undefined;
  'GiftTransferTON': undefined;
  'GiftTransferConfirmButtonFree': undefined;
  'RemoveGiftDescriptionTitle': undefined;
  'RemoveGiftDescriptionConfirmText': undefined;
  'RemoveGiftDescriptionSuccessMessage': undefined;
  'GiftUpgradeUniqueTitle': undefined;
  'GiftUpgradeUniqueDescription': undefined;
  'GiftUpgradeTransferableTitle': undefined;
  'GiftUpgradeTransferableDescription': undefined;
  'GiftUpgradeTradeableTitle': undefined;
  'GiftUpgradeTradeableDescription': undefined;
  'GiftUpgradeTitle': undefined;
  'GiftUpgradeTextOwn': undefined;
  'GiftUpgradeKeepDetails': undefined;
  'GiftUpgradedTitle': undefined;
  'GiftUpgradedDescription': undefined;
  'GiftUpgradeSentTitle': undefined;
  'GiftMakeUniqueAcc': undefined;
  'GiftMakeUniqueLink': undefined;
  'GiftWithdrawTitle': undefined;
  'GiftWithdrawSubmit': undefined;
  'AllGiftsCategory': undefined;
  'PremiumGiftDescription': undefined;
  'StarsReactionLinkText': undefined;
  'StarsReactionLink': undefined;
  'SentGift': undefined;
  'StarsSubscribeInfoLinkText': undefined;
  'StarsSubscribeInfoLink': undefined;
  'StarsBalance': undefined;
  'OpenApp': undefined;
  'PopularApps': undefined;
  'SearchApps': undefined;
  'Apps': undefined;
  'AreYouSureCloseMiniApps': undefined;
  'CloseMiniApps': undefined;
  'DoNotAskAgain': undefined;
  'PaymentInfoDone': undefined;
  'DeleteMyAccount': undefined;
  'DeleteAccountIfAwayFor': undefined;
  'SelfDestructTitle': undefined;
  'SelfDestructSessionsDescription': undefined;
  'VideoConversionTitle': undefined;
  'VideoConversionText': undefined;
  'VideoConversionDone': undefined;
  'VideoConversionView': undefined;
  'BotSuggestedStatusTitle': undefined;
  'BotSuggestedStatusUpdated': undefined;
  'BotDownloadFileTitle': undefined;
  'BotDownloadFileButton': undefined;
  'PrivacyGifts': undefined;
  'PrivacyGiftsTitle': undefined;
  'PrivacyGiftsInfo': undefined;
  'PrivacyAcceptedGiftTitle': undefined;
  'PrivacyAcceptedGiftInfo': undefined;
  'PrivacyValueBots': undefined;
  'PrivacyGiftLimitedEdition': undefined;
  'PrivacyGiftUnlimited': undefined;
  'PrivacyGiftUnique': undefined;
  'PrivacyGiftPremiumSubscription': undefined;
  'PrivacyDisplayGiftsButton': undefined;
  'PrivacyDisplayGift': undefined;
  'SendDisallowError': undefined;
  'PrivacySubscribeToTelegramPremium': undefined;
  'PrivacyDisableLimitedEditionStarGifts': undefined;
  'PrivacyEnableLimitedEditionStarGifts': undefined;
  'PrivacyDisableUnlimitedStarGifts': undefined;
  'PrivacyEnableUnlimitedStarGifts': undefined;
  'PrivacyDisableUniqueStarGifts': undefined;
  'PrivacyEnableUniqueStarGifts': undefined;
  'PrivacyDisablePremiumGifts': undefined;
  'PrivacyEnablePremiumGifts': undefined;
  'DisplayGiftsButton': undefined;
  'HideGiftsButton': undefined;
  'Review': undefined;
  'CheckPrivacyCallsText': undefined;
  'CheckPrivacyInviteText': undefined;
  'CustomShareGiftsInfo': undefined;
  'AllChatsSearchContext': undefined;
  'PrivateChatsSearchContext': undefined;
  'GroupChatsSearchContext': undefined;
  'ChannelsSearchContext': undefined;
  'FolderLinkSubtitleNew': undefined;
  'FolderLinkSubtitleAlready': undefined;
  'FolderLinkAddFolder': undefined;
  'SearchTabChats': undefined;
  'SearchTabChannels': undefined;
  'SearchTabApps': undefined;
  'SearchTabMedia': undefined;
  'SearchTabLinks': undefined;
  'SearchTabFiles': undefined;
  'SearchTabMusic': undefined;
  'SearchTabVoice': undefined;
  'SearchTabMessages': undefined;
  'SearchTabPublicPosts': undefined;
  'SearchResultTopics': undefined;
  'SearchResultMyChannels': undefined;
  'SearchResultRecommendedChannels': undefined;
  'StarsTransactionsAll': undefined;
  'StarsTransactionsIncoming': undefined;
  'StarsTransactionsOutgoing': undefined;
  'ProfileTabSavedDialogs': undefined;
  'ProfileTabStories': undefined;
  'ProfileTabStoriesArchive': undefined;
  'ProfileTabGifts': undefined;
  'ProfileTabSubscribers': undefined;
  'ProfileTabMembers': undefined;
  'ProfileTabBotPreview': undefined;
  'ProfileTabMedia': undefined;
  'ProfileTabFiles': undefined;
  'ProfileTabLinks': undefined;
  'ProfileTabMusic': undefined;
  'ProfileTabVoice': undefined;
  'ProfileTabGifs': undefined;
  'ProfileTabSharedGroups': undefined;
  'ProfileTabSimilarChannels': undefined;
  'ProfileTabSimilarBots': undefined;
  'ProfileTabPublicPosts': undefined;
  'ActionUnsupportedTitle': undefined;
  'ActionUnsupportedDescription': undefined;
  'UnlockMoreSimilarBots': undefined;
  'GiftWasNotFound': undefined;
  'ViewButtonRequestJoin': undefined;
  'ViewButtonMessage': undefined;
  'ViewButtonBot': undefined;
  'ViewButtonVoiceChat': undefined;
  'ViewButtonVoiceChatChannel': undefined;
  'ViewButtonGroup': undefined;
  'ViewButtonChannel': undefined;
  'ViewButtonUser': undefined;
  'ViewButtonBotApp': undefined;
  'ViewChatList': undefined;
  'ViewButtonStory': undefined;
  'ViewButtonBoost': undefined;
  'ViewButtonStickerset': undefined;
  'ViewButtonEmojiset': undefined;
  'ViewButtonGiftUnique': undefined;
  'AuthContinueOnThisLanguage': undefined;
  'Share': undefined;
  'GiftSortByDate': undefined;
  'GiftSortByValue': undefined;
  'GiftFilterUnlimited': undefined;
  'GiftFilterLimited': undefined;
  'GiftFilterUnique': undefined;
  'GiftFilterDisplayed': undefined;
  'GiftFilterHidden': undefined;
  'GiftFilterUpgradable': undefined;
  'GiftSearchEmpty': undefined;
  'GiftSearchReset': undefined;
  'SetUp2FA': undefined;
  'CheckPasswordTitle': undefined;
  'CheckPasswordPlaceholder': undefined;
  'CheckPasswordDescription': undefined;
  'PasswordFormPlaceholder': undefined;
  'PasswordFormSubmit': undefined;
  'ActionFallbackUser': undefined;
  'ActionFallbackChat': undefined;
  'ActionFallbackChannel': undefined;
  'ActionFallbackSomeone': undefined;
  'ActionUnsupported': undefined;
  'ActionPinnedNotFoundYou': undefined;
  'ActionPinnedMediaPhoto': undefined;
  'ActionPinnedMediaVideo': undefined;
  'ActionPinnedMediaAudio': undefined;
  'ActionPinnedMediaVoice': undefined;
  'ActionPinnedMediaVideoMessage': undefined;
  'ActionPinnedMediaFile': undefined;
  'ActionPinnedMediaGif': undefined;
  'ActionPinnedMediaContact': undefined;
  'ActionPinnedMediaLocation': undefined;
  'ActionPinnedMediaSticker': undefined;
  'ActionPinnedMediaInvoice': undefined;
  'ActionPinnedMediaStory': undefined;
  'ActionPinnedMediaAlbum': undefined;
  'ActionPinnedMediaPoll': undefined;
  'ActionPinnedMediaGiveaway': undefined;
  'ActionPinnedMediaGiveawayResults': undefined;
  'ActionGroupCallStartedChannel': undefined;
  'ActionExpiredVoice': undefined;
  'ActionExpiredVideo': undefined;
  'ActionChannelJoinedYou': undefined;
  'ActionChannelJoinedByRequestChannelYou': undefined;
  'ActionUserLeftYou': undefined;
  'ActionUserJoinedYou': undefined;
  'ActionJoinedByRequestYou': undefined;
  'ActionRemovedPhotoYou': undefined;
  'ActionRemovedPhotoChannel': undefined;
  'ActionChangedPhotoYou': undefined;
  'ActionChangedPhotoChannel': undefined;
  'ActionCreatedChannel': undefined;
  'ActionScreenshotTakenYou': undefined;
  'ActionBotAppPlaceholder': undefined;
  'ActionGiftTextUnknown': undefined;
  'ActionGiftTextUnknownYou': undefined;
  'ActionGiftUniqueSent': undefined;
  'ActionStarGiftUpgradedSelf': undefined;
  'ActionStarGiftTransferredSelf': undefined;
  'ActionStarGiftTransferredUnknown': undefined;
  'ActionStarGiftNoConvertTextYou': undefined;
  'ActionStarGiftDisplaying': undefined;
  'ActionStarGiftChannelDisplaying': undefined;
  'ActionStarGiftUpgradeTextYou': undefined;
  'ActionStarGiftUpgraded': undefined;
  'ActionStarGiftUnpack': undefined;
  'ActionStarGiftUniqueRibbon': undefined;
  'ActionStarGiftUniqueModel': undefined;
  'ActionStarGiftUniqueBackdrop': undefined;
  'ActionStarGiftUniqueSymbol': undefined;
  'ActionStarGiftSelf': undefined;
  'ActionSuggestedPhotoButton': undefined;
  'ActionSuggestedVideoTitle': undefined;
  'ActionSuggestedVideoText': undefined;
  'ActionSuggestedPhotoUpdatedTitle': undefined;
  'ActionSuggestedPhotoUpdatedDescription': undefined;
  'ActionAttachMenuBotAllowed': undefined;
  'ActionWebappBotAllowed': undefined;
  'ActionTopicClosedInside': undefined;
  'ActionTopicReopenedInside': undefined;
  'ActionTopicHiddenInside': undefined;
  'ActionTopicUnhiddenInside': undefined;
  'ActionTopicPlaceholder': undefined;
  'ActionGiveawayResultsSome': undefined;
  'ActionGiveawayResultsStarsSome': undefined;
  'ActionGiveawayResultsNone': undefined;
  'ActionOpenGiftButton': undefined;
  'ActionViewButton': undefined;
  'ActionGiveawayResultTitle': undefined;
  'ActionGiftPremiumText': undefined;
  'ActionGiftStarsText': undefined;
  'ActionHistoryCleared': undefined;
  'Refunded': undefined;
  'UniqueStatusBenefitsDescription': undefined;
  'UniqueStatusBadgeBenefitTitle': undefined;
  'UniqueStatusBadgeDescription': undefined;
  'UniqueStatusProfileDesignBenefitTitle': undefined;
  'UniqueStatusProfileDesignDescription': undefined;
  'UniqueStatusProofOfOwnershipBenefitTitle': undefined;
  'UniqueStatusProofOfOwnershipDescription': undefined;
  'UniqueStatusWearButton': undefined;
  'CollectibleStatusesCategory': undefined;
  'PeerPersonalAccount': undefined;
  'PeerChannel': undefined;
  'WebAppCollapse': undefined;
  'GiftPremiumPayWithStarsAcc': undefined;
  'GetMoreStarsLinkText': undefined;
  'StarsGiftCompleted': undefined;
  'GiftSent': undefined;
  'PrivacyDescriptionMessagesContactsAndPremium': undefined;
  'PrivacyChargeForMessages': undefined;
  'PrivacyDescriptionChargeForMessages': undefined;
  'RemoveFeeTitle': undefined;
  'ExceptionTitlePrivacyChargeForMessages': undefined;
  'ExceptionDescriptionPrivacyChargeForMessages': undefined;
  'SectionTitleStarsForForMessages': undefined;
  'SubtitlePrivacyAddUsers': undefined;
  'PrivacyPaidMessagesValue': undefined;
  'ButtonBuyStars': undefined;
  'TitleConfirmPayment': undefined;
  'ButtonUndo': undefined;
  'ConfirmRemoveMessageFee': undefined;
  'StoryTooltipGifSent': undefined;
  'StoryTooltipStickerSent': undefined;
  'StoryTooltipReactionSent': undefined;
  'StarsNeededTextSendPaidMessages': undefined;
  'PaidMessageTransactionTotal': undefined;
  'TitleFrozenAccount': undefined;
  'SubtitleFrozenAccount': undefined;
  'ComposerTitleFrozenAccount': undefined;
  'ComposerSubtitleFrozenAccount': undefined;
  'DescriptionRestrictedMedia': undefined;
  'DescriptionScheduledPaidMediaNotAllowed': undefined;
  'DescriptionScheduledPaidMessagesNotAllowed': undefined;
  'GroupMessagesChargePrice': undefined;
  'RightsChargeStarsAbout': undefined;
  'UnlockButtonTitle': undefined;
  'FrozenAccountModalTitle': undefined;
  'FrozenAccountViolationTitle': undefined;
  'FrozenAccountViolationSubtitle': undefined;
  'FrozenAccountReadOnlyTitle': undefined;
  'FrozenAccountReadOnlySubtitle': undefined;
  'FrozenAccountAppealTitle': undefined;
  'ButtonAppeal': undefined;
  'ButtonUnderstood': undefined;
  'ActionPaidMessagePriceFreeYou': undefined;
  'NotificationTitleNotSupportedInFrozenAccount': undefined;
  'NotificationMessageNotSupportedInFrozenAccount': undefined;
  'NotificationMessageTextHidden': undefined;
  'GiftRibbonSale': undefined;
  'StarsGiftBought': undefined;
  'GiftSellTitle': undefined;
  'Sell': undefined;
  'InputPlaceholderGiftResalePrice': undefined;
  'StarGiftSaleTransaction': undefined;
  'StarGiftPurchaseTransaction': undefined;
  'ContextMenuItemMention': undefined;
  'GiftRibbonResale': undefined;
  'GiftCategoryCollectibles': undefined;
  'GiftCategoryMyGifts': undefined;
  'GiftSortByPrice': undefined;
  'GiftSortByNumber': undefined;
  'ContextMenuItemSelectAll': undefined;
  'ValueGiftSortByDate': undefined;
  'ValueGiftSortByPrice': undefined;
  'ValueGiftSortByNumber': undefined;
  'ResellGiftsNoFound': undefined;
  'ResellGiftsClearFilters': undefined;
  'SendInStandardQuality': undefined;
  'SendInHighQuality': undefined;
  'MonoforumBadge': undefined;
  'MonoforumStatus': undefined;
  'MonoforumComposerPlaceholder': undefined;
  'ChannelSendMessage': undefined;
  'AutomaticTranslation': undefined;
  'ComposerEmbeddedMessageSuggestedPostTitle': undefined;
  'ComposerEmbeddedMessageSuggestedPostDescription': undefined;
  'ActionSuggestedPostOutgoing': undefined;
  'ActionSuggestedChangesPrice': undefined;
  'ActionSuggestedChangesText': undefined;
  'ActionSuggestedChangesTime': undefined;
  'ActionSuggestedChangesMedia': undefined;
  'TitlePrice': undefined;
  'TitleTime': undefined;
  'TitleSuggestMessage': undefined;
  'TitleSuggestedChanges': undefined;
  'SuggestMessageNoPrice': undefined;
  'EnterPriceInStars': undefined;
  'EnterPriceInTon': undefined;
  'SuggestMessagePriceDescriptionStars': undefined;
  'SuggestMessagePriceDescriptionTon': undefined;
  'SuggestMessageDateTimeHint': undefined;
  'SuggestMessageAnytime': undefined;
  'ButtonOfferFree': undefined;
  'ButtonUpdateTerms': undefined;
  'InputPlaceholderPrice': undefined;
  'SuggestedPostApprove': undefined;
  'SuggestedPostDecline': undefined;
  'SuggestedPostSuggestChanges': undefined;
  'InputTitleSuggestMessageTime': undefined;
  'SuggestedPostApproved': undefined;
  'SuggestedPostRejectedNotification': undefined;
  'SuggestedPostAgreementReached': undefined;
  'CurrencyStars': undefined;
  'CurrencyTon': undefined;
  'DeclineReasonPlaceholder': undefined;
  'SuggestedPostRejectedYou': undefined;
  'SuggestedPostRejectedWithReasonYou': undefined;
  'ComposerPlaceholderCaption': undefined;
  'SuggestedPostConfirmTitle': undefined;
  'ButtonPublish': undefined;
  'PublishNow': undefined;
  'TitleNewToDoList': undefined;
  'TitleEditToDoList': undefined;
  'TitleAppendToDoList': undefined;
  'InputTitle': undefined;
  'TitleToDoList': undefined;
  'TitleTask': undefined;
  'TitleAddTask': undefined;
  'AllowOthersAddTasks': undefined;
  'AllowOthersMarkAsDone': undefined;
  'AriaToDoCancel': undefined;
  'TitleGroupToDoList': undefined;
  'TitleYourToDoList': undefined;
  'MenuButtonAppendTodoList': undefined;
  'PremiumMore': undefined;
  'SubscribeToTelegramPremiumForToggleTask': undefined;
  'SubscribeToTelegramPremiumForCreateToDo': undefined;
  'SubscribeToTelegramPremiumForAppendToDo': undefined;
  'ToDoListErrorChooseTitle': undefined;
  'ToDoListErrorChooseTasks': undefined;
  'PremiumPreviewTodo': undefined;
  'NativeDownloadFailed': undefined;
  'DescriptionAboutTon': undefined;
  'ButtonTopUpViaFragment': undefined;
  'TonModalHint': undefined;
  'TonGiftReceived': undefined;
  'MediaSpoilerSensitive': undefined;
  'TextSensitiveModal': undefined;
  'ButtonSensitiveView': undefined;
  'TitleAgeVerificationModal': undefined;
  'DescriptionAgeVerificationModal': undefined;
  'TitleAgeCheckFailed': undefined;
  'TitleAgeCheckSuccess': undefined;
  'ButtonAgeVerification': undefined;
  'GiftRibbonPremium': undefined;
  'PremiumGiftHeader': undefined;
  'PriceInStars': undefined;
  'PriceInTON': undefined;
  'OnlyAcceptTON': undefined;
  'OnlyAcceptTONDescription': undefined;
  'DescriptionPayInTON': undefined;
  'LabelPayInTON': undefined;
  'PriceChanged': undefined;
  'PayNewPrice': undefined;
  'LinkPreview': undefined;
  'ContextMoveTextUp': undefined;
  'ContextMoveTextDown': undefined;
  'ContextLinkLargerMedia': undefined;
  'ContextLinkSmallerMedia': undefined;
  'ContextLinkRemovePreview': undefined;
  'AccLinkRemovePreview': undefined;
  'GlobalSearch': undefined;
  'DescriptionPublicPostsSearch': undefined;
  'PublicPosts': undefined;
  'PublicPostsLimitReached': undefined;
  'PublicPostsPremiumFeatureDescription': undefined;
  'PublicPostsPremiumFeatureSubtitle': undefined;
  'PublicPostsSubscribeToPremium': undefined;
  'PostsSearchTransaction': undefined;
  'AllStoriesCategory': undefined;
  'TitleRating': undefined;
  'RatingYourReflectsActivity': undefined;
  'RatingGiftsFromTelegram': undefined;
  'RatingGiftsFromTelegramDesc': undefined;
  'RatingGiftsAndPostsFromUsers': undefined;
  'RatingGiftsAndPostsFromUsersDesc': undefined;
  'RatingRefundsAndConversions': undefined;
  'RatingRefundsAndConversionsDesc': undefined;
  'RatingBadgeAdded': undefined;
  'RatingBadgeDeducted': undefined;
  'RatingNegativeLevel': undefined;
  'LinkDescriptionRatingBack': undefined;
  'LinkDescriptionRatingPreview': undefined;
  'ErrorFocusInaccessibleMessage': undefined;
  'ContextMenuHintMouse': undefined;
  'ContextMenuHintTouch': undefined;
  'GiftValueForSaleOnFragment': undefined;
  'GiftValueForSaleOnTelegram': undefined;
  'EmbeddedMessageNoCaption': undefined;
  'ConfirmBuyGiftForTonDescription': undefined;
  'TitleGiftLocked': undefined;
  'QuickPreview': undefined;
  'BotForumContinueThreadButton': undefined;
  'BotForumActionNew': undefined;
  'BotForumActionNewDescription': undefined;
  'BotForumTopicTitlePlaceholder': undefined;
  'DropOriginalDetailsTransaction': undefined;
  'StarGiftReasonDropOriginalDetails': undefined;
  'GiftAnUpgradeButton': undefined;
  'GiftPrepaidUpgradeTransactionTitle': undefined;
  'StarGiftAuctionBidTransaction': undefined;
  'StarGiftAuctionBidRefundedTransaction': undefined;
  'ActionStarGiftPrepaidUpgradedYou': undefined;
  'UserNoteTitle': undefined;
  'UserNoteHint': undefined;
  'EditUserNoteHint': undefined;
  'BotForumAllTopicTitle': undefined;
  'BotForumAllTopicDescription': undefined;
  'AriaStoryTogglerOpen': undefined;
  'InviteBlockedTitle': undefined;
  'InviteBlockedOneMessage': undefined;
  'InviteBlockedManyMessage': undefined;
  'InviteBlockedOr': undefined;
  'InviteBlockedNoLinkTitle': undefined;
  'InviteBlockedPremiumTitle': undefined;
  'InviteBlockedPremiumButton': undefined;
  'InviteRestrictedPremiumReason': undefined;
  'InviteViaLinkButton': undefined;
  'StoryUnsupported': undefined;
  'StoryRibbonMyStory': undefined;
  'StoryMenuSavedStories': undefined;
  'StoryMenuArchivedStories': undefined;
  'StoryMenuSendMessage': undefined;
  'StoryMenuViewProfile': undefined;
  'StoryMenuViewChannel': undefined;
  'StoryMenuOpenStealth': undefined;
  'StoryMenuArchivePeer': undefined;
  'StoryMenuUnarchivePeer': undefined;
  'StealthModeOnTitle': undefined;
  'StealthModeOnHintEnabled': undefined;
  'StealthModeTitle': undefined;
  'StealthModeDescription': undefined;
  'StealthModeDescriptionPremium': undefined;
  'StealthModeHideRecentTitle': undefined;
  'StealthModeHideRecentDescription': undefined;
  'StealthModeHideFutureTitle': undefined;
  'StealthModeHideFutureDescription': undefined;
  'StealthModeButtonPremium': undefined;
  'StealthModeButton': undefined;
  'StealthModeButtonToStory': undefined;
  'UpgradeCostDrops': undefined;
  'StarGiftPriceDecreaseInfoLink': undefined;
  'StarGiftUpgradeCostModalTitle': undefined;
  'StarGiftUpgradeCostHint': undefined;
  'GiftRibbonAuction': undefined;
  'GiftAuctionJoin': undefined;
  'GiftAuctionLearnMore': undefined;
  'GiftAuctionStarted': undefined;
  'GiftAuctionEnds': undefined;
  'GiftAuctionCurrentRound': undefined;
  'GiftAuctionPlaceBid': undefined;
  'GiftAuctionMinimumBid': undefined;
  'GiftAuctionUntilNextRound': undefined;
  'GiftAuctionLeft': undefined;
  'GiftAuctionYourBidWillBe': undefined;
  'GiftAuctionYoureWinning': undefined;
  'GiftAuctionBalance': undefined;
  'GiftAuctionInfoTitle': undefined;
  'GiftAuctionInfoSubtitle': undefined;
  'GiftAuctionInfoBidCarryoverTitle': undefined;
  'GiftAuctionInfoMissedBiddersTitle': undefined;
  'GiftAuctionInfoMissedBiddersSubtitle': undefined;
  'GiftAuctionRecipient': undefined;
  'GiftAuctionDate': undefined;
  'GiftAuctionAcceptedBid': undefined;
  'GiftAuctionCustomBidTitle': undefined;
  'GiftAuctionCustomBidPlaceholder': undefined;
  'GiftAuctionCustomBidButton': undefined;
  'GiftAuctionBidPlacedTitle': undefined;
  'GiftAuctionBidIncreasedTitle': undefined;
  'GiftAuctionFinished': undefined;
  'GiftAuctionEnded': undefined;
  'GiftAuctionSoldOut': undefined;
  'GiftAuctionChangeRecipientTitle': undefined;
  'GiftAuctionAveragePrice': undefined;
  'GiftAuctionTapToBidMore': undefined;
  'StarGift': undefined;
  'SettingsItemPrivacyPasskeys': undefined;
  'SettingsItemPrivacyOn': undefined;
  'SettingsItemPrivacyOff': undefined;
  'SettingsPasskeyTitle': undefined;
  'SettingsPasskeyInfo': undefined;
  'SettingsPasskeyFallbackTitle': undefined;
  'SettingsPasskeysFooterLink': undefined;
  'SettingsPasskeysCreate': undefined;
  'PasskeyModalTitle': undefined;
  'PasskeyModalDescription': undefined;
  'PasskeyModalFeature1Title': undefined;
  'PasskeyModalFeature1Description': undefined;
  'PasskeyModalFeature2Title': undefined;
  'PasskeyModalFeature2Description': undefined;
  'PasskeyModalFeature3Title': undefined;
  'PasskeyModalFeature3Description': undefined;
  'PasskeyModalButtonText': undefined;
  'PasskeyDeleteTitle': undefined;
  'PasskeyDeleteText': undefined;
  'PasskeyCreateError': undefined;
  'PasskeyLoginError': undefined;
  'UnconfirmedAuthDeniedTitle': undefined;
  'UnconfirmedAuthTitle': undefined;
  'UnconfirmedAuthConfirm': undefined;
  'UnconfirmedAuthDeny': undefined;
  'SuggestionBirthdaySetupTitle': undefined;
  'SuggestionBirthdaySetupMessage': undefined;
  'BirthdaySetupTitle': undefined;
  'BirthdayInputDay': undefined;
  'BirthdayInputMonth': undefined;
  'BirthdayInputYear': undefined;
  'BirthdayRemove': undefined;
  'BirthdayPrivacySuggestionLink': undefined;
  'SettingsBirthday': undefined;
  'BotReadTextFromClipboardTitle': undefined;
  'BotReadTextFromClipboardConfirm': undefined;
}

export interface LangPairWithVariables<V = LangVariable> {
  'UserTyping': {
    'user': V;
  };
  'UserActionWatchingAnimations': {
    'emoji': V;
  };
  'SetUrlAvailable': {
    'url': V;
  };
  'UsernameAvailable': {
    'username': V;
  };
  'LimitReachedChatInFolders': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedFileSize': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedFolders': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedPinDialogs': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedPublicLinks': {
    'limit2': V;
  };
  'LimitReachedCommunities': {
    'limit': V;
    'limit2': V;
  };
  'LimitReachedChatInFoldersLocked': {
    'limit': V;
  };
  'LimitReachedFileSizeLocked': {
    'limit': V;
  };
  'LimitReachedFoldersLocked': {
    'limit': V;
  };
  'LimitReachedPinDialogsLocked': {
    'limit': V;
  };
  'LimitReachedCommunitiesLocked': {
    'limit': V;
  };
  'LimitReachedChatInFoldersPremium': {
    'limit': V;
  };
  'LimitReachedFileSizePremium': {
    'limit': V;
  };
  'LimitReachedFoldersPremium': {
    'limit': V;
  };
  'LimitReachedPinDialogsPremium': {
    'limit': V;
  };
  'LimitReachedCommunitiesPremium': {
    'limit': V;
  };
  'PremiumPreviewLimitsDescription': {
    'limit1': V;
    'limit2': V;
    'limit3': V;
    'limit4': V;
    'limit5': V;
  };
  'SpeakingWithVolume': {
    'volume': V;
  };
  'CallEmojiKeyTooltip': {
    'user': V;
  };
  'ConversationScheduleMessageSendToday': {
    'time': V;
  };
  'ConversationScheduleMessageSendOn': {
    'date': V;
    'time': V;
  };
  'ChatListDeleteAndLeaveGroupConfirmation': {
    'chat': V;
  };
  'ChannelLeaveAlertWithName': {
    'chat': V;
  };
  'ChatListDeleteChatConfirmation': {
    'chat': V;
  };
  'ChatListDeleteForEveryone': {
    'user': V;
  };
  'ConversationDeleteMessagesFor': {
    'user': V;
  };
  'ConversationPinMessagesFor': {
    'user': V;
  };
  'AutodownloadSizeLimitUpTo': {
    'limit': V;
  };
  'WebAppAddToAttachmentText': {
    'bot': V;
  };
  'WebAppShareMessageInfo': {
    'user': V;
  };
  'BotPermissionGameAlert': {
    'bot': V;
  };
  'BotOpenPageMessage': {
    'bot': V;
  };
  'BotSharedToOne': {
    'peer': V;
  };
  'NewContactPhoneHiddenText': {
    'user': V;
  };
  'AddContactSharedContactExceptionInfo': {
    'user': V;
  };
  'SubscribeToPremium': {
    'price': V;
  };
  'TelegramPremiumUserDialogTitle': {
    'user': V;
  };
  'OpenUrlText': {
    'url': V;
  };
  'ConversationOpenBotLinkLogin': {
    'url': V;
    'user': V;
  };
  'ConversationOpenBotLinkAllowMessages': {
    'bot': V;
  };
  'BlockUserTitle': {
    'user': V;
  };
  'UserInfoBlockConfirmationTitle': {
    'user': V;
  };
  'ReportChat': {
    'peer': V;
  };
  'SlowModePlaceholder': {
    'timer': V;
  };
  'SlowModeHint': {
    'time': V;
  };
  'ErrorFloodTime': {
    'time': V;
  };
  'ErrorPasswordFresh': {
    'time': V;
  };
  'ErrorUnexpectedMessage': {
    'error': V;
  };
  'EditedDate': {
    'date': V;
  };
  'ForwardedDate': {
    'date': V;
  };
  'CallMessageWithDuration': {
    'time': V;
    'duration': V;
  };
  'MessageScheduledOn': {
    'date': V;
  };
  'MessageTooltipEditedDate': {
    'date': V;
  };
  'MessageTooltipForwardedDate': {
    'date': V;
  };
  'EmptyGroupInfoLine1': {
    'count': V;
  };
  'PaymentCheckoutAcceptRecurrent': {
    'bot': V;
  };
  'CheckoutPayPrice': {
    'amount': V;
  };
  'PeerInfoConfirmRemovePeer': {
    'user': V;
  };
  'EditAdminPromotedBy': {
    'user': V;
  };
  'UserRemovedBy': {
    'user': V;
  };
  'DiscussionUnlinkChannelAlert': {
    'chat': V;
  };
  'DiscussionUnlinkGroupAlert': {
    'channel': V;
  };
  'AreYouSureDeleteThisChatWithGroup': {
    'chat': V;
  };
  'LinkExpiresIn': {
    'time': V;
  };
  'InviteLinkExpiresIn': {
    'time': V;
  };
  'UsernameByPhoneNotFound': {
    'phone': V;
  };
  'LimitReachedFavoriteGifs': {
    'count': V;
  };
  'LimitReachedFavoriteGifsSubtitle': {
    'count': V;
  };
  'LimitReachedFavoriteStickers': {
    'count': V;
  };
  'LimitReachedFavoriteStickersSubtitle': {
    'count': V;
  };
  'VoipPeerIncompatible': {
    'user': V;
  };
  'NewDiscussionChatTitle': {
    'name': V;
  };
  'AttachInvoice': {
    'description': V;
  };
  'LastSeenTodayAt': {
    'time': V;
  };
  'LastSeenYesterdayAt': {
    'time': V;
  };
  'LastSeenAtDate': {
    'date': V;
  };
  'ChannelPermissionDeniedSendMessagesUntil': {
    'date': V;
  };
  'FormatDateAtTime': {
    'date': V;
    'time': V;
  };
  'GroupsAndChannelsLimitSubtitle': {
    'count': V;
  };
  'PinChatsLimitSubtitle': {
    'count': V;
  };
  'PublicLinksLimitSubtitle': {
    'count': V;
  };
  'SavedGifsLimitSubtitle': {
    'count': V;
  };
  'FavoriteStickersLimitSubtitle': {
    'count': V;
  };
  'FoldersLimitSubtitle': {
    'count': V;
  };
  'ChatPerFolderLimitSubtitle': {
    'count': V;
  };
  'ChatOutgoingContextMixedReactionCount': {
    'count': V;
    'total': V;
  };
  'ScheduleRepeat': {
    'value': V;
  };
  'MessageTimerShortHours': {
    'count': V;
  };
  'MessageTimerShortDays': {
    'count': V;
  };
  'LiveLocationUpdatedTodayAt': {
    'time': V;
  };
  'AtDateAgo': {
    'date': V;
  };
  'MediaViewDownloading': {
    'count': V;
  };
  'ComposerPlaceholderTopic': {
    'topic': V;
  };
  'ChannelManagementLinkDiscussion': {
    'group': V;
    'channel': V;
  };
  'ProfileOpenAppAbout': {
    'terms': V;
  };
  'ProfileBirthdayValue': {
    'date': V;
  };
  'ProfileBirthdayValueYear': {
    'date': V;
    'age': V;
  };
  'ProfileBirthdayTodayValue': {
    'date': V;
  };
  'ProfileBirthdayTodayValueYear': {
    'date': V;
    'age': V;
  };
  'ChannelEarnLearnCoinAbout': {
    'link': V;
  };
  'MonetizationBalanceZeroInfo': {
    'link': V;
  };
  'ChannelEarnAbout': {
    'link': V;
  };
  'CreditsBoxHistoryEntryGiftOutAbout': {
    'user': V;
    'link': V;
  };
  'StarsTransactionTOS': {
    'link': V;
  };
  'GiftStarsOutgoing': {
    'user': V;
  };
  'GiftPremiumDescription': {
    'user': V;
    'link': V;
  };
  'StarGiftDescription': {
    'user': V;
  };
  'StarGiftDescriptionChannel': {
    'peer': V;
  };
  'GiftDiscount': {
    'percent': V;
  };
  'GiftSoldCount': {
    'count': V;
  };
  'GiftLeftCount': {
    'count': V;
  };
  'GiftHideNameDescription': {
    'receiver': V;
  };
  'GiftSend': {
    'amount': V;
  };
  'GiftUnique': {
    'title': V;
    'number': V;
  };
  'GiftInfoPeerDescriptionOutRegular': {
    'peer': V;
  };
  'GiftInfoPeerDescriptionFreeUpgradeOut': {
    'peer': V;
  };
  'GiftInfoPeerConvertDescription': {
    'peer': V;
    'amount': V;
  };
  'UserUpdatedName': {
    'user': V;
    'time': V;
  };
  'UserUpdatedPhoto': {
    'user': V;
    'time': V;
  };
  'GiftInfoSaved': {
    'link': V;
  };
  'GiftInfoHidden': {
    'link': V;
  };
  'GiftInfoChannelSaved': {
    'link': V;
  };
  'GiftInfoChannelHidden': {
    'link': V;
  };
  'GiftInfoTonText': {
    'link': V;
  };
  'GiftValueDescription': {
    'giftName': V;
  };
  'GiftInfoIssued': {
    'issued': V;
    'total': V;
  };
  'GiftInfoCollectible': {
    'number': V;
  };
  'GiftSavedNumber': {
    'number': V;
  };
  'GiftInfoPeerOriginalInfo': {
    'peer': V;
    'date': V;
  };
  'GiftInfoPeerOriginalInfoSender': {
    'sender': V;
    'peer': V;
    'date': V;
  };
  'GiftInfoPeerOriginalInfoText': {
    'peer': V;
    'date': V;
    'text': V;
  };
  'GiftInfoPeerOriginalInfoTextSender': {
    'sender': V;
    'peer': V;
    'date': V;
    'text': V;
  };
  'GiftTransferTONBlocked': {
    'time': V;
  };
  'GiftTransferConfirmDescription': {
    'gift': V;
    'peer': V;
    'amount': V;
  };
  'GiftTransferConfirmDescriptionFree': {
    'gift': V;
    'peer': V;
  };
  'GiftTransferConfirmButton': {
    'amount': V;
  };
  'GiftTransferSuccessMessage': {
    'gift': V;
    'peer': V;
  };
  'RemoveGiftDescriptionButton': {
    'amount': V;
  };
  'GiftPeerUpgradeText': {
    'peer': V;
  };
  'GiftUpgradeButton': {
    'amount': V;
  };
  'GiftPayForUpgradeButton': {
    'amount': V;
  };
  'GiftPeerUpgradeUniqueDescription': {
    'user': V;
  };
  'GiftPeerUpgradeTransferableDescription': {
    'user': V;
  };
  'GiftPeerUpgradeTradeableDescription': {
    'user': V;
  };
  'GiftUpgradeSentMessage': {
    'user': V;
  };
  'GiftMakeUnique': {
    'stars': V;
  };
  'GiftMakeUniqueDescription': {
    'user': V;
    'link': V;
  };
  'GiftMakeUniqueDescriptionChannel': {
    'peer': V;
    'link': V;
  };
  'GiftWithdrawDescription': {
    'gift': V;
  };
  'StarsAmount': {
    'amount': V;
  };
  'SendPaidReaction': {
    'amount': V;
  };
  'StarsPay': {
    'amount': V;
  };
  'StarsReactionTerms': {
    'link': V;
  };
  'AriaMiniApp': {
    'bot': V;
  };
  'StarsSubscribeInfo': {
    'link': V;
  };
  'StarsPerMonth': {
    'amount': V;
  };
  'EmojiStatusAccessText': {
    'name': V;
  };
  'BotSuggestedStatusFor': {
    'bot': V;
    'duration': V;
  };
  'BotSuggestedStatus': {
    'bot': V;
  };
  'BotDownloadFileDescription': {
    'bot': V;
    'filename': V;
  };
  'PrivacyDisplayGiftIconInChats': {
    'icon': V;
    'gift': V;
  };
  'StarsSubscribeBotButtonMonth': {
    'amount': V;
  };
  'SearchContextCaption': {
    'type': V;
  };
  'FolderLinkTitleDescription': {
    'folder': V;
    'chats': V;
  };
  'FolderLinkSubtitleAdd': {
    'chats': V;
    'title': V;
  };
  'FolderLinkNotificationDeletedTitle': {
    'title': V;
  };
  'FolderLinkNotificationAddedTitle': {
    'title': V;
  };
  'FolderLinkNotificationUpdatedTitle': {
    'title': V;
  };
  'LocationPermissionText': {
    'name': V;
  };
  'ActionPinnedText': {
    'from': V;
    'text': V;
  };
  'ActionPinnedTextYou': {
    'text': V;
  };
  'ActionPinnedNotFound': {
    'from': V;
  };
  'ActionPinnedMedia': {
    'from': V;
    'media': V;
  };
  'ActionPinnedMediaYou': {
    'media': V;
  };
  'ActionPinnedMediaGame': {
    'game': V;
  };
  'ActionGroupCallStartedGroup': {
    'from': V;
  };
  'ActionGroupCallScheduledGroup': {
    'from': V;
    'date': V;
  };
  'ActionGroupCallScheduledChannel': {
    'date': V;
  };
  'ActionGroupCallFinishedChannel': {
    'duration': V;
  };
  'ActionGroupCallFinishedGroup': {
    'from': V;
    'duration': V;
  };
  'ActionAddUser': {
    'from': V;
    'user': V;
  };
  'ActionAddUserYou': {
    'user': V;
  };
  'ActionAddUsersMany': {
    'from': V;
    'users': V;
  };
  'ActionAddUsersManyYou': {
    'users': V;
  };
  'ActionAddYou': {
    'from': V;
  };
  'ActionAddYouGroup': {
    'from': V;
  };
  'ActionKickUser': {
    'from': V;
    'user': V;
  };
  'ActionKickUserYou': {
    'user': V;
  };
  'ActionUserLeft': {
    'from': V;
  };
  'ActionUserJoined': {
    'from': V;
  };
  'ActionUserJoinedByLink': {
    'from': V;
  };
  'ActionJoinedByRequest': {
    'from': V;
  };
  'ActionVideoInvited': {
    'from': V;
    'user': V;
  };
  'ActionVideoInvitedYou': {
    'user': V;
  };
  'ActionVideoInvitedMany': {
    'from': V;
    'users': V;
  };
  'ActionVideoInvitedManyYou': {
    'users': V;
  };
  'ActionUserRegistered': {
    'from': V;
  };
  'ActionRemovedPhoto': {
    'from': V;
  };
  'ActionChangedPhoto': {
    'from': V;
  };
  'ActionChangedTitle': {
    'from': V;
    'title': V;
  };
  'ActionChangedTitleYou': {
    'title': V;
  };
  'ActionChangedTitleChannel': {
    'title': V;
  };
  'ActionCreatedChat': {
    'from': V;
    'title': V;
  };
  'ActionCreatedChatYou': {
    'title': V;
  };
  'ActionPaymentDone': {
    'amount': V;
    'user': V;
  };
  'ActionPaymentDoneFor': {
    'amount': V;
    'user': V;
    'invoice': V;
  };
  'ActionPaymentInitRecurringFor': {
    'amount': V;
    'user': V;
    'invoice': V;
  };
  'ActionPaymentInitRecurring': {
    'amount': V;
    'user': V;
  };
  'ActionPaymentUsedRecurring': {
    'amount': V;
  };
  'ActionScreenshotTaken': {
    'from': V;
  };
  'ActionBotAllowedFromDomain': {
    'domain': V;
  };
  'ActionBotAllowedFromApp': {
    'app': V;
  };
  'ActionGiftTextCost': {
    'from': V;
    'cost': V;
  };
  'ActionGiftTextCostYou': {
    'cost': V;
  };
  'ActionGiftTextCostAnonymous': {
    'cost': V;
  };
  'ActionCostCrypto': {
    'price': V;
    'cryptoPrice': V;
  };
  'ActionWebviewDataDone': {
    'text': V;
  };
  'ActionGiftUniqueReceived': {
    'user': V;
  };
  'ActionStarGiftReceived': {
    'user': V;
    'cost': V;
  };
  'ActionStarGiftSent': {
    'cost': V;
  };
  'ActionStarGiftUpgradedUser': {
    'user': V;
  };
  'ActionStarGiftUpgradedChannel': {
    'user': V;
    'channel': V;
  };
  'ActionStarGiftUpgradedChannelYou': {
    'channel': V;
  };
  'ActionStarGiftUpgradedMine': {
    'user': V;
  };
  'ActionStarGiftTransferred': {
    'user': V;
  };
  'ActionStarGiftTransferredChannel': {
    'user': V;
    'channel': V;
  };
  'ActionStarGiftTransferredChannelYou': {
    'channel': V;
  };
  'ActionStarGiftTransferredMine': {
    'user': V;
  };
  'ActionStarGiftTransferredUnknownChannel': {
    'channel': V;
  };
  'ActionStarGiftReceivedAnonymous': {
    'cost': V;
  };
  'ActionStarGiftSentChannel': {
    'user': V;
    'channel': V;
    'cost': V;
  };
  'ActionStarGiftSentChannelYou': {
    'channel': V;
    'cost': V;
  };
  'ActionStarGiftPrepaidUpgradeYou': {
    'cost': V;
    'peer': V;
  };
  'ActionStarGiftPrepaidUpgrade': {
    'peer': V;
    'cost': V;
  };
  'ActionStarGiftSelfBought': {
    'cost': V;
  };
  'ActionStarGiftTo': {
    'peer': V;
  };
  'ActionStarGiftFrom': {
    'peer': V;
  };
  'ActionStarGiftConvertText': {
    'peer': V;
    'amount': V;
  };
  'ActionStarGiftConvertTextYou': {
    'amount': V;
  };
  'ActionStarGiftNoConvertText': {
    'peer': V;
  };
  'ActionStarGiftConvertedText': {
    'peer': V;
    'amount': V;
  };
  'ActionStarGiftConvertedTextYou': {
    'amount': V;
  };
  'ActionStarGiftChannelText': {
    'amount': V;
  };
  'ActionStarGiftUpgradeText': {
    'peer': V;
  };
  'ActionStarGiftLimitedRibbon': {
    'total': V;
  };
  'ActionStarGiftAuctionWon': {
    'cost': V;
  };
  'ActionStarGiftAuctionFor': {
    'peer': V;
  };
  'ActionStarGiftAuctionBought': {
    'cost': V;
  };
  'ActionSuggestedPhotoYou': {
    'user': V;
  };
  'ActionSuggestedPhoto': {
    'user': V;
  };
  'ActionTopicCreated': {
    'topic': V;
  };
  'ActionTopicClosed': {
    'from': V;
    'topic': V;
  };
  'ActionTopicReopened': {
    'from': V;
    'topic': V;
  };
  'ActionTopicHidden': {
    'topic': V;
  };
  'ActionTopicUnhidden': {
    'topic': V;
  };
  'ActionTopicRenamed': {
    'from': V;
    'link': V;
    'title': V;
  };
  'ActionTopicIconChanged': {
    'from': V;
    'link': V;
    'emoji': V;
  };
  'ActionTopicIconRemoved': {
    'from': V;
    'link': V;
  };
  'ActionTopicIconAndRenamed': {
    'from': V;
    'link': V;
    'topic': V;
  };
  'ActionGiveawayStartedGroup': {
    'from': V;
  };
  'ActionGiveawayStarted': {
    'from': V;
  };
  'ActionGiveawayStarsStartedGroup': {
    'from': V;
    'amount': V;
  };
  'ActionGiveawayStarsStarted': {
    'from': V;
    'amount': V;
  };
  'ActionGiveawayResultPremiumDuration': {
    'channel': V;
    'duration': V;
  };
  'ActionGiftCodeSubscriptionDuration': {
    'peer': V;
    'duration': V;
  };
  'ActionGiftCodeSubscriptionDurationYou': {
    'peer': V;
    'duration': V;
  };
  'ActionGiftPremiumDuration': {
    'duration': V;
  };
  'TonAmount': {
    'amount': V;
  };
  'ActionGiftCostCrypto': {
    'cryptoPrice': V;
    'price': V;
  };
  'ActionPaymentRefunded': {
    'peer': V;
    'amount': V;
  };
  'ActionMigratedFrom': {
    'chat': V;
  };
  'ActionMigratedTo': {
    'chat': V;
  };
  'UniqueStatusWearTitle': {
    'gift': V;
  };
  'GiftPremiumStarsPrice': {
    'stars': V;
  };
  'GiftPremiumPayWithStars': {
    'stars': V;
  };
  'GiftPremiumDescriptionYourBalance': {
    'stars': V;
    'link': V;
  };
  'SectionDescriptionStarsForForMessages': {
    'percent': V;
    'amount': V;
  };
  'MessagesPlaceholderPaidUser': {
    'peer': V;
    'amount': V;
  };
  'MessagesPlaceholderPaidChannel': {
    'peer': V;
    'amount': V;
  };
  'ComposerPlaceholderPaidMessage': {
    'amount': V;
  };
  'ComposerPlaceholderPaidReply': {
    'amount': V;
  };
  'MessageSentPaidToastText': {
    'amount': V;
  };
  'ActionPaidOneMessageOutgoing': {
    'amount': V;
  };
  'ActionPaidOneMessageIncoming': {
    'user': V;
    'amount': V;
  };
  'PaneMessagePaidMessageCharge': {
    'peer': V;
    'amount': V;
  };
  'ConfirmDialogMessageRemoveFee': {
    'peer': V;
  };
  'ConfirmDialogRemoveFeeRefundStars': {
    'amount': V;
  };
  'PaidMessageTransactionDescription': {
    'percent': V;
  };
  'SetPriceGroupDescription': {
    'percent': V;
    'amount': V;
  };
  'FrozenAccountAppealSubtitle': {
    'botLink': V;
    'date': V;
  };
  'ActionPaidMessagePrice': {
    'peer': V;
    'amount': V;
  };
  'ActionPaidMessagePriceYou': {
    'amount': V;
  };
  'ActionPaidMessagePriceFree': {
    'peer': V;
  };
  'ActionMessageChannelFree': {
    'peer': V;
  };
  'ActionMessageChannelDisabled': {
    'peer': V;
  };
  'ApiMessageActionPaidMessagesRefundedOutgoing': {
    'stars': V;
    'user': V;
  };
  'ApiMessageActionPaidMessagesRefundedIncoming': {
    'user': V;
    'stars': V;
  };
  'NotificationGiftIsSale': {
    'gift': V;
  };
  'NotificationGiftIsUnlist': {
    'gift': V;
  };
  'ButtonBuyGift': {
    'stars': V;
  };
  'GiftInfoBuyGift': {
    'user': V;
  };
  'ButtonSellGift': {
    'stars': V;
  };
  'DescriptionComposerGiftResalePrice': {
    'stars': V;
  };
  'DescriptionComposerGiftMinimumPrice': {
    'stars': V;
  };
  'ApiMessageMessageActionResaleStarGiftUniqueOutgoing': {
    'stars': V;
    'gift': V;
  };
  'ApiMessageMessageActionResaleStarGiftUniqueIncoming': {
    'stars': V;
    'gift': V;
  };
  'ModalStarsBalanceBarDescription': {
    'stars': V;
  };
  'NotificationGiftCanResellAt': {
    'date': V;
  };
  'NotificationGiftCanTransferAt': {
    'date': V;
  };
  'GiftBuyConfirmDescription': {
    'gift': V;
    'stars': V;
  };
  'GiftBuyForPeerConfirmDescription': {
    'gift': V;
    'stars': V;
    'peer': V;
  };
  'GiftBuyEqualsTo': {
    'stars': V;
  };
  'ComposerTitleForwardFrom': {
    'users': V;
  };
  'TitleSuggestedPostAmountForAnyTime': {
    'amount': V;
  };
  'ActionSuggestedPostIncoming': {
    'user': V;
  };
  'ActionSuggestedChangesOutgoing': {
    'changes': V;
  };
  'ActionSuggestedChangesIncoming': {
    'user': V;
    'changes': V;
  };
  'SuggestMessageTimeDescription': {
    'hint': V;
    'duration': V;
  };
  'ButtonOfferAmount': {
    'amount': V;
  };
  'SuggestedPostPublishSchedule': {
    'peer': V;
    'date': V;
  };
  'SuggestedPostPublishScheduleYou': {
    'peer': V;
    'date': V;
  };
  'SuggestedPostPublished': {
    'peer': V;
    'date': V;
  };
  'SuggestedPostPublishedYou': {
    'peer': V;
    'date': V;
  };
  'SuggestedPostCharged': {
    'user': V;
    'amount': V;
  };
  'SuggestedPostChargedYou': {
    'amount': V;
  };
  'SuggestedPostReceiveAmount': {
    'peer': V;
    'duration': V;
  };
  'SuggestedPostReceiveAmountYou': {
    'peer': V;
    'duration': V;
  };
  'SuggestedPostRefund': {
    'peer': V;
    'duration': V;
  };
  'SuggestedPostRefundYou': {
    'peer': V;
    'duration': V;
  };
  'SuggestedPostBalanceTooLow': {
    'peer': V;
    'currency': V;
  };
  'SuggestedPostRefundedByUser': {
    'channel': V;
    'amount': V;
    'user': V;
  };
  'SuggestedPostRefundedByChannel': {
    'amount': V;
    'peer': V;
    'channel': V;
  };
  'DeclinePostDialogQuestion': {
    'sender': V;
  };
  'SuggestedPostRejected': {
    'peer': V;
  };
  'SuggestedPostRejectedWithReason': {
    'peer': V;
  };
  'SuggestedPostRejectedComment': {
    'comment': V;
  };
  'ActionSuggestedPostSuccess': {
    'channel': V;
    'amount': V;
  };
  'DescriptionSuggestedPostMinimumOffer': {
    'amount': V;
  };
  'SuggestedPostConfirmMessage': {
    'peer': V;
  };
  'SuggestedPostConfirmDetailsAdmin': {
    'amount': V;
    'commission': V;
    'duration': V;
  };
  'SuggestedPostConfirmDetailsUser': {
    'amount': V;
    'duration': V;
  };
  'SuggestedPostConfirmDetailsWithTimeAdmin': {
    'amount': V;
    'commission': V;
    'time': V;
    'duration': V;
  };
  'SuggestedPostConfirmDetailsWithTimeUser': {
    'amount': V;
    'time': V;
    'duration': V;
  };
  'ButtonPublishAtTime': {
    'time': V;
  };
  'TitleUserToDoList': {
    'peer': V;
  };
  'DescriptionCompletedToDoTasks': {
    'number': V;
    'count': V;
  };
  'MessageActionTodoCompletionsAsDone': {
    'peer': V;
    'task': V;
  };
  'MessageActionTodoCompletionsAsDoneYou': {
    'task': V;
  };
  'MessageActionTodoCompletionsAsDoneMultiple': {
    'peer': V;
    'tasks': V;
  };
  'MessageActionTodoCompletionsAsDoneMultipleYou': {
    'tasks': V;
  };
  'MessageActionTodoCompletionsAsNotDone': {
    'peer': V;
    'task': V;
  };
  'MessageActionTodoCompletionsAsNotDoneYou': {
    'task': V;
  };
  'MessageActionTodoCompletionsAsNotDoneMultiple': {
    'peer': V;
    'tasks': V;
  };
  'MessageActionTodoCompletionsAsNotDoneMultipleYou': {
    'tasks': V;
  };
  'MessageActionAppendTodo': {
    'peer': V;
    'task': V;
    'list': V;
  };
  'MessageActionAppendTodoYou': {
    'task': V;
    'list': V;
  };
  'MessageActionAppendTodoMultiple': {
    'peer': V;
    'tasks': V;
    'list': V;
  };
  'MessageActionAppendTodoMultipleYou': {
    'tasks': V;
    'list': V;
  };
  'GiftInfoCollectibleBy': {
    'number': V;
    'owner': V;
  };
  'TitleSensitiveModal': {
    'years': V;
  };
  'ButtonSensitiveAlways': {
    'years': V;
  };
  'DialogTitlePremiumGiftSentTo': {
    'user': V;
    'amount': V;
  };
  'DialogTitlePremiumGiftReceivedFrom': {
    'user': V;
    'amount': V;
  };
  'DescriptionComposerGiftMinimumCurrencyPrice': {
    'amount': V;
  };
  'DescriptionComposerGiftResaleCurrencyPrice': {
    'amount': V;
  };
  'ButtonSellGiftTon': {
    'amount': V;
  };
  'PriceChangedText': {
    'originalAmount': V;
    'newAmount': V;
  };
  'ButtonSearchPublicPosts': {
    'query': V;
  };
  'PublicPostsSearchForStars': {
    'stars': V;
  };
  'UnlockTimerPublicPostsSearch': {
    'time': V;
  };
  'NotificationPaidExtraSearch': {
    'stars': V;
  };
  'RatingReflectsActivity': {
    'name': V;
  };
  'RatingLevel': {
    'level': V;
  };
  'GiftLockedMessage': {
    'relativeDate': V;
  };
  'ActionStarGiftPrepaidUpgraded': {
    'user': V;
  };
  'FileTransferProgress': {
    'currentSize': V;
    'totalSize': V;
  };
  'InviteRestrictedPremiumReasonSingle': {
    'user': V;
  };
  'InviteRestrictedPremiumReasonMultiple': {
    'list': V;
  };
  'StealthModeOnHint': {
    'time': V;
  };
  'StealthModeButtonRecharge': {
    'timer': V;
  };
  'StealthModeComposerPlaceholder': {
    'timer': V;
  };
  'StarGiftPriceDecreaseTimer': {
    'timer': V;
  };
  'GiftAuctionRoundValue': {
    'current': V;
    'total': V;
  };
  'GiftAuctionPlaceBidButton': {
    'amount': V;
  };
  'GiftAuctionTimeLeft': {
    'time': V;
  };
  'GiftAuctionAddToBid': {
    'amount': V;
  };
  'GiftAuctionInfoBidCarryoverSubtitle': {
    'count': V;
  };
  'GiftAuctionBoughtGiftHeader': {
    'gift': V;
    'giftNumber': V;
    'round': V;
  };
  'GiftAuctionTopPosition': {
    'position': V;
  };
  'GiftAuctionCustomBidDescription': {
    'count': V;
  };
  'GiftAuctionBidPlacedMessage': {
    'count': V;
  };
  'GiftAuctionChangeRecipientDescription': {
    'oldPeer': V;
    'newPeer': V;
  };
  'GiftAuctionWonNotification': {
    'gift': V;
  };
  'SettingsPasskeyUsedAt': {
    'date': V;
  };
  'SettingsPasskeysFooter': {
    'link': V;
  };
  'UnconfirmedAuthDeniedMessage': {
    'location': V;
  };
  'UnconfirmedAuthSingle': {
    'location': V;
  };
  'UnconfirmedAuthLocationRegion': {
    'deviceModel': V;
    'region': V;
    'country': V;
  };
  'UnconfirmedAuthLocationCountry': {
    'deviceModel': V;
    'country': V;
  };
  'BirthdayPrivacySuggestion': {
    'link': V;
  };
  'BotReadTextFromClipboardDescription': {
    'bot': V;
  };
}

export interface LangPairPlural {
  'DeleteForMeChatHint': undefined;
  'DeleteForEveryoneHint': undefined;
  'PreviewDraggingAddItems': undefined;
  'MediaReplaceInvalidError': undefined;
}

export interface LangPairPluralWithVariables<V = LangVariable> {
  'Participants': {
    'count': V;
  };
  'OnlineCount': {
    'count': V;
  };
  'Subscribers': {
    'count': V;
  };
  'NMembers': {
    'count': V;
  };
  'ChatUnpinAllMessagesConfirmation': {
    'count': V;
  };
  'GroupInfoParticipantCount': {
    'count': V;
  };
  'Weeks': {
    'count': V;
  };
  'Months': {
    'count': V;
  };
  'Users': {
    'count': V;
  };
  'StickerPackStickerCount': {
    'count': V;
  };
  'PreviewSenderSendPhoto': {
    'count': V;
  };
  'PreviewSenderSendVideo': {
    'count': V;
  };
  'PreviewSenderSendAudio': {
    'count': V;
  };
  'PreviewSenderSendFile': {
    'count': V;
  };
  'PinnedMessageTitle': {
    'index': V;
  };
  'Comments': {
    'count': V;
  };
  'ChatContextReactionCount': {
    'count': V;
  };
  'ConversationContextMenuSeen': {
    'count': V;
  };
  'Answer': {
    'count': V;
  };
  'VoiceOverChatMessagesSelected': {
    'count': V;
  };
  'ChatPinnedUnpinAll': {
    'count': V;
  };
  'CommentsCount': {
    'count': V;
  };
  'PinnedMessagesCount': {
    'count': V;
  };
  'Messages': {
    'count': V;
  };
  'MessageTooltipForwards': {
    'count': V;
  };
  'MessageTooltipViews': {
    'count': V;
  };
  'MessageTooltipReplies': {
    'count': V;
  };
  'Hours': {
    'count': V;
  };
  'Days': {
    'count': V;
  };
  'PeopleJoined': {
    'count': V;
  };
  'PeopleCanJoinViaLinkCount': {
    'count': V;
  };
  'CanJoin': {
    'count': V;
  };
  'JoinRequests': {
    'count': V;
  };
  'ChannelStatsViewsCount': {
    'count': V;
  };
  'ChannelStatsSharesCount': {
    'count': V;
  };
  'ChatsPlural': {
    'count': V;
  };
  'LastSeenMinutesAgo': {
    'count': V;
  };
  'LastSeenHoursAgo': {
    'count': V;
  };
  'MessageRepeatPeriodEveryMinutes': {
    'count': V;
  };
  'MessageRepeatPeriodEveryMonths': {
    'count': V;
  };
  'StickerPackRemoveStickerCount': {
    'count': V;
  };
  'StickerPackAddStickerCount': {
    'count': V;
  };
  'ScheduleRepeatEveryMinutes': {
    'count': V;
  };
  'ScheduleRepeatEveryMonths': {
    'count': V;
  };
  'Years': {
    'count': V;
  };
  'LiveLocationUpdatedMinutesAgo': {
    'count': V;
  };
  'Seconds': {
    'count': V;
  };
  'Minutes': {
    'count': V;
  };
  'MinutesAgo': {
    'count': V;
  };
  'HoursAgo': {
    'count': V;
  };
  'DaysAgo': {
    'count': V;
  };
  'PreviewForwardedMessage': {
    'count': V;
  };
  'SearchMessagesFound': {
    'count': V;
  };
  'ShowMoreChats': {
    'count': V;
  };
  'ShowMoreVoters': {
    'count': V;
  };
  'GiftInfoDescription': {
    'amount': V;
  };
  'GiftInfoPeerDescriptionOut': {
    'peer': V;
    'amount': V;
  };
  'GiftInfoDescriptionUpgrade': {
    'amount': V;
  };
  'GiftInfoDescriptionConverted': {
    'amount': V;
  };
  'GiftInfoPeerDescriptionOutConverted': {
    'peer': V;
    'amount': V;
  };
  'GiftInfoConvert': {
    'amount': V;
  };
  'GiftInfoConvertDescriptionPeriod': {
    'count': V;
  };
  'GiftInfoAvailabilityValue': {
    'count': V;
    'total': V;
  };
  'GiftWithdrawWait': {
    'days': V;
  };
  'ChatGroups': {
    'count': V;
  };
  'StarsAmountText': {
    'amount': V;
  };
  'MiniAppsMoreTabs': {
    'botName': V;
    'count': V;
  };
  'PrizeCredits2': {
    'count': V;
  };
  'StarsSubscribeText': {
    'chat': V;
    'amount': V;
  };
  'StarsSubscribeBotText': {
    'name': V;
    'bot': V;
    'amount': V;
  };
  'FolderLinkTitleDescriptionChats': {
    'count': V;
  };
  'FolderLinkSubtitleAddCount': {
    'count': V;
  };
  'FolderLinkNotificationDeletedSubtitle': {
    'count': V;
  };
  'FolderLinkNotificationAddedSubtitle': {
    'count': V;
  };
  'FolderLinkNotificationUpdatedSubtitle': {
    'count': V;
  };
  'MoreSimilarBotsDescription': {
    'count': V;
  };
  'ActionGameScore': {
    'from': V;
    'count': V;
    'game': V;
  };
  'ActionGameScoreYou': {
    'count': V;
    'game': V;
  };
  'ActionGameScoreNoGame': {
    'from': V;
    'count': V;
  };
  'ActionGameScoreNoGameYou': {
    'count': V;
  };
  'ActionGiveawayResults': {
    'count': V;
  };
  'ActionGiveawayResultsStars': {
    'count': V;
  };
  'ActionGiveawayResultPremiumText': {
    'channel': V;
    'months': V;
  };
  'ActionGiftCodePremiumText': {
    'channel': V;
    'months': V;
  };
  'ActionGiveawayResultStarsText': {
    'channel': V;
    'amount': V;
  };
  'ActionGiftCodeSubscriptionText': {
    'peer': V;
    'months': V;
  };
  'ActionGiftCodeSubscriptionTextYou': {
    'peer': V;
    'months': V;
  };
  'ActionGiftPremiumTitle': {
    'months': V;
  };
  'ActionGiftStarsTitle': {
    'amount': V;
  };
  'TonAmountText': {
    'amount': V;
  };
  'ActionBoostApplyYou': {
    'count': V;
  };
  'ActionBoostApply': {
    'from': V;
    'count': V;
  };
  'ConfirmationModalPaymentForMessage': {
    'user': V;
    'amount': V;
    'totalAmount': V;
    'count': V;
  };
  'PayForMessage': {
    'count': V;
  };
  'MessageSentPaidToastTitle': {
    'count': V;
  };
  'PaidMessageTransaction': {
    'count': V;
  };
  'HeaderDescriptionResaleGifts': {
    'count': V;
  };
  'GiftAttributeModelPlural': {
    'count': V;
  };
  'GiftAttributeBackdropPlural': {
    'count': V;
  };
  'GiftAttributeSymbolPlural': {
    'count': V;
  };
  'MessageActionTodoTaskCount': {
    'count': V;
  };
  'HintTodoListTasksCount2': {
    'count': V;
  };
  'TextAgeVerificationModal': {
    'count': V;
  };
  'NotificationGiftsLimit2': {
    'count': V;
  };
  'DescriptionGiftPremiumRequired2': {
    'count': V;
  };
  'RemainingPublicPostsSearch': {
    'count': V;
  };
  'HintPublicPostsSearchQuota': {
    'count': V;
  };
  'DescriptionPendingRating': {
    'time': V;
    'points': V;
    'link': V;
  };
  'DescriptionFutureRating': {
    'time': V;
    'points': V;
    'link': V;
  };
  'MediaSizeB': {
    'size': V;
  };
  'MediaSizeKB': {
    'size': V;
  };
  'MediaSizeMB': {
    'size': V;
  };
  'MediaSizeGB': {
    'size': V;
  };
  'InviteRestrictedUsers': {
    'count': V;
  };
  'InviteRestrictedPremiumReasonMultipleMore': {
    'list': V;
    'count': V;
  };
  'GiftAuctionTopBidders': {
    'count': V;
    'gift': V;
    'link': V;
  };
  'GiftAuctionDescription': {
    'count': V;
    'link': V;
  };
  'GiftAuctionTopWinners': {
    'count': V;
  };
  'GiftAuctionInfoTopBiddersTitle': {
    'count': V;
  };
  'GiftAuctionInfoTopBiddersSubtitle': {
    'count': V;
  };
  'GiftAuctionItemsBought': {
    'count': V;
    'gift': V;
  };
  'GiftAuctionBoughtGiftsTitle': {
    'count': V;
  };
  'GiftAuctionGifts': {
    'count': V;
  };
}
export type RegularLangKey = keyof LangPair;
export type RegularLangKeyWithVariables = keyof LangPairWithVariables;
export type PluralLangKey = keyof LangPairPlural;
export type PluralLangKeyWithVariables = keyof LangPairPluralWithVariables;
export type LangKey = RegularLangKey | RegularLangKeyWithVariables | PluralLangKey | PluralLangKeyWithVariables;
type LangVariable = string | number | undefined;
