import { P2PPayloadType } from './p2pMessage';
import type { PayloadType } from './types';
export declare function toTelegramSource(source: number): number;
export declare function fromTelegramSource(source: number): number;
export declare function getAmplitude(array: Uint8Array, scale?: number): number;
export declare function p2pPayloadTypeToConference(p: P2PPayloadType): PayloadType;
export declare const THRESHOLD = 0.1;
export declare const IS_SCREENSHARE_SUPPORTED: boolean;
export declare const IS_ECHO_CANCELLATION_SUPPORTED: boolean | undefined;
export declare const IS_NOISE_SUPPRESSION_SUPPORTED: any;
